import test from 'node:test';import assert from 'node:assert/strict';
import {StageInput} from '../dist/input/stage.js';import {canvasCoordinate,canvasPairView,pairAngle} from '../dist/input/canvas-view.js';
import {object,project,History,clone} from '../dist/document/model.js';import {configureAutoKey,evaluated} from '../dist/animation/evaluate.js';import {sceneSVG} from '../dist/renderer/svg.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} differs from ${b}`),rotate=(p,deg)=>{const a=deg*Math.PI/180;return {x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)};};
function fixture(n=object('rectangle',{x:100,y:100})){const a={doc:project(),selected:[n.id],tool:'select',time:2,autoKey:true,ease:'linear',multi:false,nodeEdit:false,snap:false,audio:{},properties:{flush(){}},pause(){},render(){},renderStage(){},toast(){}};a.doc.width=1000;a.doc.height=600;a.doc.layers=[n];configureAutoKey(a.doc,true,'linear');a.history=new History(()=>a.doc,p=>{a.doc=p;configureAutoKey(a.doc,true,'linear');});const s=Object.create(StageInput.prototype);Object.assign(s,{a,fitScale:1,pointers:new Map(),view:{zoom:1,x:0,y:0,rotation:0},el:{setPointerCapture(){},getBoundingClientRect:()=>({left:120,top:50,width:1024,height:768})},overlay:{innerHTML:''},layout(){}});s.svg={getBoundingClientRect:()=>{const v=s.view,r=(v.rotation||0)*Math.PI/180,w=(Math.abs(Math.cos(r))*a.doc.width+Math.abs(Math.sin(r))*a.doc.height)*v.zoom,h=(Math.abs(Math.sin(r))*a.doc.width+Math.abs(Math.cos(r))*a.doc.height)*v.zoom;return {left:632+v.x-w/2,top:434+v.y-h/2,width:w,height:h};}};return s;}
function screen(s,p){const q=rotate({x:(p.x-s.a.doc.width/2)*s.view.zoom,y:(p.y-s.a.doc.height/2)*s.view.zoom},s.view.rotation||0);return {clientX:632+s.view.x+q.x,clientY:434+s.view.y+q.y};}
function ev(s,id,p,extra={}){return {button:0,pointerType:'touch',pointerId:id,...p,preventDefault(){},target:{closest:q=>q==='[data-id]'?{dataset:{id:s.a.selected[0]}}:null},...extra};}
function env(fn){const old={document:globalThis.document,setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout},timers=new Map();let id=0;globalThis.document={activeElement:null};globalThis.setTimeout=(f,ms)=>{timers.set(++id,{f,ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);try{fn({fire(){for(const [id,t] of [...timers])if(t.ms===300){timers.delete(id);t.f();}}});}finally{Object.assign(globalThis,old);}}
test('production two-finger twist rotates the view around its midpoint without changing artwork, keys or SVG export',()=>env(()=>{
 const s=fixture(),before=clone(s.a.doc),svg=sceneSVG(s.a.doc,2);s.down(ev(s,1,{clientX:500,clientY:300}));s.down(ev(s,2,{clientX:700,clientY:300}));const anchor=s.coord({clientX:600,clientY:300});s.move(ev(s,1,{clientX:600,clientY:200}));s.move(ev(s,2,{clientX:600,clientY:400}));near(s.view.rotation,90);near(s.view.zoom,1);const now=s.coord({clientX:600,clientY:300});near(now.x,anchor.x);near(now.y,anchor.y);s.up(ev(s,1,{clientX:600,clientY:200}));s.up(ev(s,2,{clientX:600,clientY:400}));assert.deepEqual(s.a.doc,before);assert.equal(sceneSVG(s.a.doc,2),svg);assert.equal(s.a.history.undoStack.length,0);
}));
test('combined pan, pinch and twist preserves the initial finger anchor at the final midpoint under an existing rotated zoomed view',()=>{
 const initial=[{clientX:410,clientY:280},{clientX:590,clientY:280}],g={distance:180,angle:pairAngle(initial),mid:{x:500,y:280},view:{zoom:1.4,x:35,y:-20,rotation:30}},center={x:632,y:434},final=[{clientX:680,clientY:330},{clientX:680,clientY:690}],v=canvasPairView(g,final,center),oldAnchor={x:500-center.x-g.view.x,y:280-center.y-g.view.y},mapped=rotate(oldAnchor,90);near(v.zoom,2.8);near(v.rotation,120);near(center.x+v.x+mapped.x*2,680);near(center.y+v.y+mapped.y*2,510);
});
test('canvas twist unwraps angular boundaries and multiple turns instead of jumping at 180 degrees',()=>{
 const pair=deg=>{const p=rotate({x:100,y:0},deg);return [{clientX:0,clientY:0},{clientX:p.x,clientY:p.y}];},g={distance:100,angle:pairAngle(pair(170)),mid:{x:0,y:0},view:{zoom:1,x:0,y:0,rotation:0}};let view;for(const d of [190,230,270,310,350,390,430,470,510,550])view=canvasPairView(g,pair(d),{x:0,y:0});near(view.rotation,380);
});
test('held two-finger pan locks existing angle and zoom while preserving quick two-tap Undo',()=>env(c=>{
 const s=fixture();s.view={zoom:2,x:20,y:-10,rotation:45};s.down(ev(s,1,{clientX:500,clientY:300}));s.down(ev(s,2,{clientX:700,clientY:300}));c.fire();s.move(ev(s,1,{clientX:550,clientY:320}));s.move(ev(s,2,{clientX:750,clientY:320}));assert.deepEqual(s.view,{zoom:2,x:70,y:10,rotation:45});s.up(ev(s,1,{clientX:550,clientY:320}));s.up(ev(s,2,{clientX:750,clientY:320}));assert.equal(s.a.history.undoStack.length,0);
 s.a.history.run('Earlier edit',()=>s.a.doc.layers[0].name='Edited');s.down(ev(s,3,{clientX:500,clientY:300}));s.down(ev(s,4,{clientX:700,clientY:300}));s.up(ev(s,3,{clientX:500,clientY:300}));s.up(ev(s,4,{clientX:700,clientY:300}));assert.equal(s.a.doc.layers[0].name,'Rectangle');near(s.view.rotation,45);
}));
test('rotated coordinate fallback inverts arbitrary angles, zoom, pan and page offsets, including the 45-degree bounding-box ambiguity',()=>{
 const s=fixture();for(const angle of [0,45,90,137,-75,405])for(const zoom of [.3,1,3]){s.view={zoom,x:37,y:-52,rotation:angle};for(const p of [{x:0,y:0},{x:1000,y:600},{x:225,y:413}]){const q=s.coord(screen(s,p));near(q.x,p.x);near(q.y,p.y);}}
 s.svg.getScreenCTM=()=>{throw Error('Unavailable');};s.view.rotation=45;near(s.coord(screen(s,{x:23,y:44})).x,23);
});
test('SVG screen CTM inverse takes priority over bounding rectangle and uses client coordinates',()=>{
 const svg={getScreenCTM:()=>({inverse:()=>({a:0,b:-.5,c:.5,d:0,e:-50,f:200})}),getBoundingClientRect(){throw Error('Should not use bounding rectangle');}};assert.deepEqual(canvasCoordinate(svg,{width:1000,height:600},{rotation:90},{clientX:300,clientY:200}),{x:50,y:50});
});
test('drawing and artwork dragging after canvas rotation use document coordinates and key artwork rather than the view',()=>env(()=>{
 const s=fixture();s.view={zoom:1.7,x:30,y:-40,rotation:63};const n=s.a.doc.layers[0],down=ev(s,1,screen(s,{x:130,y:140}),{pointerType:'mouse'});s.down(down);s.move({...down,...screen(s,{x:160,y:180})});s.up({...down,...screen(s,{x:160,y:180})});near(evaluated(n,2).x,130);near(evaluated(n,2).y,140);near(evaluated(n,0).x,100);near(s.view.rotation,63);
 s.a.tool='rect';const blank=ev(s,2,screen(s,{x:300,y:200}),{pointerType:'mouse',target:{closest:()=>null}});s.down(blank);s.move({...blank,...screen(s,{x:420,y:280})});s.up({...blank,...screen(s,{x:420,y:280})});const drawn=s.a.doc.layers.at(-1);near(drawn.x,300);near(drawn.y,200);near(drawn.width,120);near(drawn.height,80);
}));
test('layout rotates the shared SVG/overlay shell; zoom retains the angle and Fit restores upright view',()=>env(()=>{
 const s=fixture(),label={};s.el.clientWidth=1024;s.el.clientHeight=624;s.shell={style:{}};s.overlay.setAttribute=()=>{};globalThis.document.querySelector=()=>label;s.layout=StageInput.prototype.layout;s.view={zoom:2,x:30,y:-10,rotation:45};s.layout();assert.equal(s.shell.style.width,'2000px');assert.equal(s.shell.style.transform,'translate(30px,-10px) rotate(45deg)');s.zoom(1.5);near(s.view.rotation,45);near(s.view.zoom,3);s.fit();assert.deepEqual(s.view,{zoom:1,x:0,y:0,rotation:0});assert.equal(s.shell.style.transform,'translate(0px,0px)');
}));
test('joining a materialized rectangle or Pencil stroke with a second finger commits visible artwork once before view navigation',()=>env(()=>{
 for(const tool of ['rect','pencil']){const s=fixture(),before=clone(s.a.doc);s.a.tool=tool;const first=ev(s,1,screen(s,{x:300,y:200}),{target:{closest:()=>null}}),end={...first,...screen(s,{x:420,y:280})};s.down(first);s.move(end);const drawn=s.a.doc.layers.at(-1),drawnState=clone(drawn);s.down(ev(s,2,screen(s,{x:600,y:280}),{target:{closest:()=>null}}));assert.equal(s.g.tapCandidate,false);assert.deepEqual(s.a.doc.layers.at(-1),drawnState);assert.equal(s.a.history.undoStack.length,1);assert.equal(s.a.history.before,null);s.move({...end,...screen(s,{x:440,y:300})});s.cancel(ev(s,2,screen(s,{x:620,y:300})));s.up(end);assert.equal(s.a.doc.layers.length,2);assert.equal(s.a.history.undoStack.length,1);s.a.history.undo();assert.deepEqual(s.a.doc,before);}
}));
test('a Pen path with a live dragged anchor survives second-finger navigation with its curve and one Undo',()=>env(()=>{
 const s=fixture(),before=clone(s.a.doc);s.a.tool='path';const blank=(id,p)=>ev(s,id,screen(s,p),{target:{closest:()=>null}});s.down(blank(1,{x:300,y:200}));s.up(blank(1,{x:300,y:200}));s.down(blank(1,{x:420,y:280}));s.move(blank(1,{x:460,y:300}));const path=clone(s.a.doc.layers.at(-1));s.down(blank(2,{x:600,y:280}));assert.equal(s.path,null);assert.equal(s.g.tapCandidate,false);assert.deepEqual(s.a.doc.layers.at(-1),path);assert.equal(s.a.history.undoStack.length,1);s.up(blank(1,{x:460,y:300}));s.up(blank(2,{x:600,y:280}));assert.equal(s.a.doc.layers.length,2);assert.equal(s.a.history.undoStack.length,1);s.a.history.undo();assert.deepEqual(s.a.doc,before);
}));
test('second finger cancels unmaterialized shape taps and one-point strokes/paths without Undoing an earlier edit',()=>env(()=>{
 for(const tool of ['rect','pencil','path']){const s=fixture();s.a.history.run('Earlier edit',()=>s.a.doc.layers[0].name='Keep this');const before=clone(s.a.doc);s.a.tool=tool;const first=ev(s,1,screen(s,{x:300,y:200}),{target:{closest:()=>null}}),second=ev(s,2,screen(s,{x:450,y:200}),{target:{closest:()=>null}});s.down(first);s.down(second);assert.equal(s.g.tapCandidate,false);s.up(first);s.up(second);assert.deepEqual(s.a.doc,before);assert.equal(s.a.history.undoStack.length,1);assert.equal(s.a.history.before,null);}
}));
