import test from 'node:test';import assert from 'node:assert/strict';
import {object,project,clone} from '../dist/document/model.js';import {validate} from '../dist/document/validate.js';
import {PreviewRenderer,sceneSVG,artwork} from '../dist/renderer/svg.js';import {shadowPaintBounds,shadowRegion} from '../dist/scene/shadow.js';import {motionBlurSamples} from '../dist/animation/motion-blur.js';import {evaluated} from '../dist/animation/evaluate.js';
const key=(id,time,value)=>({id,time,value,easing:'linear'});
const filterBounds=markup=>[...markup.matchAll(/<filter id="[^"]+"[^>]* x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"/g)].map(m=>({x:Number(m[1]),y:Number(m[2]),width:Number(m[3]),height:Number(m[4])}));
function movingChild(){return object('rectangle',{id:'child',width:100,height:100,motionBlur:{enabled:true,shutterAngle:360,samples:7},tracks:{x:[key('x0',0,0),key('x1',2,6000)]}});}
test('a group shadow contains the actual child blur trail at composition FPS in normal preview and export',()=>{const p=project();p.fps=12;const c=movingChild(),g=object('group',{id:'group',shadowEnabled:true,shadowBlur:0,shadowX:0,shadowY:0,children:[c]});p.layers=[g];const region=shadowRegion(g,shadowPaintBounds(g,1,undefined,{fps:p.fps,duration:p.duration}));assert.ok(region.x<2875);assert.ok(region.x+region.width>3225);const original=globalThis.document;try{globalThis.document={createElementNS:()=>({childNodes:[],set innerHTML(s){}})};const renderer=new PreviewRenderer({childNodes:[],setAttribute(){}});renderer.render(p,1);for(const markup of [renderer.cache,sceneSVG(p,1)]){const b=filterBounds(markup)[0];assert.ok(b.x<2875&&b.x+b.width>3225);assert.equal((markup.match(/data-blur-time=/g)||[]).length,7);}renderer.dispose();}finally{globalThis.document=original;}const faster=shadowRegion(g,shadowPaintBounds(g,1,undefined,{fps:60,duration:p.duration}));assert.ok(faster.width<region.width);});
test('parent temporal sampling suppresses descendant sampling in shadow bounds, keeping only the current sampled subtree pose',()=>{const c=movingChild(),nested=object('group',{id:'nested',motionBlur:{enabled:true,shutterAngle:360,samples:7},children:[c]}),g=object('group',{id:'outer',shadowEnabled:true,shadowBlur:0,children:[nested],motionBlur:{enabled:true,shutterAngle:360,samples:7}}),p=project();p.layers=[g];const current=shadowPaintBounds(g,1,undefined,{fps:12,duration:5,suppressMotionBlur:true});assert.ok(current.x>=2997);assert.ok(current.x+current.width<=3103);const rendered=artwork(g,1,false,false,undefined,{fps:12,duration:5});assert.equal((rendered.match(/data-motion-blur=/g)||[]).length,1);assert.equal(filterBounds(rendered).length,7);});
test('group bounds include animated child geometry and its own shadow at every rendered shutter time',()=>{const c=movingChild();c.type='path';c.closed=true;c.nodes=[{x:0,y:0},{x:100,y:0},{x:100,y:100}];c.tracks.nodes=[key('n0',0,clone(c.nodes)),key('n1',2,[{x:0,y:0},{x:300,y:0},{x:300,y:200}])];Object.assign(c,{shadowEnabled:true,shadowX:150,shadowY:-90,shadowBlur:20});const g=object('group',{children:[c]});const b=shadowPaintBounds(g,1,undefined,{fps:12,duration:5});for(const sample of motionBlurSamples(c,1,12,5)){const v=evaluated(c,sample.time),child=shadowRegion(v,shadowPaintBounds(c,sample.time));assert.ok(b.x<=v.x+child.x);assert.ok(b.x+b.width>=v.x+child.x+child.width);assert.ok(b.y<=child.y);assert.ok(b.y+b.height>=child.y+child.height);}});
test('applied animated shadow and blur survive portable reload and render from current geometry without a preview map',()=>{const p=project();p.fps=12;const n=object('path',{id:'path',closed:true,nodes:[{x:0,y:0},{x:100,y:0},{x:100,y:100}],shadowEnabled:true,shadowBlur:0,shadowX:60,shadowY:0,motionBlur:{enabled:true,shutterAngle:360,samples:7}});n.tracks.nodes=[key('n0',0,clone(n.nodes)),key('n1',2,[{x:0,y:0},{x:400,y:0},{x:400,y:300}])];p.layers=[n];const restored=validate(JSON.parse(JSON.stringify(p))),before=JSON.stringify(restored),markup=sceneSVG(restored,1);assert.equal((markup.match(/data-blur-time=/g)||[]).length,7);const bs=filterBounds(markup);assert.equal(bs.length,7);assert.ok(bs.every(b=>b.width>300));const refs=[...markup.matchAll(/filter="url\(#([^\)]+)\)"/g)].map(m=>m[1]);for(const id of refs)assert.ok(markup.includes('id="'+id+'"'));assert.equal(JSON.stringify(restored),before);});
