import {object,project} from '../dist/document/model.js';import {createMesh} from '../dist/scene/mesh.js';
import test from 'node:test';import assert from 'node:assert/strict';import {StageInput} from '../dist/input/stage.js';
test('two-finger tap undoes once only after both fingers lift; moving and long holds do not undo',()=>{
 for(const scenario of ['tap','move','hold']){let undos=0;const points=new Map([[1,{x:100,y:100}],[2,{x:150,y:100}]]),stage={a:{history:{undo(){undos++;}},toast(){},render(){}},owner:1,pointers:new Map([[1,{}],[2,{}]]),g:{type:'pinch',tapCandidate:true,startedAt:Date.now()-(scenario==='hold'?1000:10),tapPoints:points},clearMeshHold(){}};Object.setPrototypeOf(stage,StageInput.prototype);
 StageInput.prototype.up.call(stage,{pointerId:1,clientX:scenario==='move'?120:100,clientY:100});assert.equal(undos,0);
 StageInput.prototype.up.call(stage,{pointerId:2,clientX:150,clientY:100});assert.equal(undos,scenario==='tap'?1:0);assert.equal(stage.g,null);
 }
});
test('mesh hold opens the selected colour picker; release cancels its timer',()=>{
 const oldTimeout=globalThis.setTimeout,oldClear=globalThis.clearTimeout,oldDoc=globalThis.document;let callback,delay,cleared=0,opened=0,cancelled=0,styled=0,closePicker,previewCleared=0;
 globalThis.setTimeout=(fn,ms)=>{callback=fn;delay=ms;return 42;};globalThis.clearTimeout=()=>{cleared++;};globalThis.document={querySelector:()=>({disabled:false,showPicker(){opened++;}})};
 try{const doc=project(),n=object('rectangle',{mesh:createMesh({x:0,y:0,width:100,height:100})});doc.layers=[n];const stage={a:{doc,selected:[n.id],time:0,pause(){},properties:{flush(){}},dialog(title,body,apply,options){opened++;assert.match(title,/Mesh point 1 colour/);assert.match(body,/Apply colour/);assert.equal(options.modal,false);const hex={value:'#ffffff'},preview={style:{}},palette={insertAdjacentHTML(position,html){assert.equal(position,'beforebegin');assert.match(html,/Last 10 colours/);}};return {classList:{add(name){assert.equal(name,'object-colour-dialog');styled++;}},addEventListener(type,fn,opts){assert.equal(type,'close');assert.equal(opts.once,true);closePicker=fn;},querySelectorAll(){return [];},querySelector(selector){if(selector==='.mesh-palette')return palette;if(selector==='[name=colour]')return hex;if(selector==='[data-colour-preview]')return preview;throw Error('Unexpected picker query: '+selector);}};},renderStage(){previewCleared++;},history:{cancel(){cancelled++;}},render(){}},g:{type:'mesh'},owner:1,pointers:new Map([[1,{}]]),clearMeshHold:StageInput.prototype.clearMeshHold};Object.setPrototypeOf(stage,StageInput.prototype);StageInput.prototype.startMeshHold.call(stage,{clientX:100,clientY:100});assert.equal(delay,550);callback();assert.equal(opened,1);assert.equal(cancelled,1);assert.equal(stage.g,null);assert.equal(styled,1);closePicker();assert.equal(previewCleared,1);
 stage.g={type:'mesh'};StageInput.prototype.startMeshHold.call(stage,{clientX:100,clientY:100});StageInput.prototype.up.call(stage,{pointerId:1,clientX:100,clientY:100});assert.ok(cleared>=2);assert.equal(stage.meshHoldTimer,undefined);
 }finally{globalThis.setTimeout=oldTimeout;globalThis.clearTimeout=oldClear;if(oldDoc===undefined)delete globalThis.document;else globalThis.document=oldDoc;}
});
