import {object,project} from '../dist/document/model.js';import {createMesh} from '../dist/scene/mesh.js';
import test from 'node:test';import assert from 'node:assert/strict';import {StageInput} from '../dist/input/stage.js';
test('two-finger tap undoes once only after both fingers lift; moving and long holds do not undo',()=>{
 for(const scenario of ['tap','move','hold']){let undos=0;const points=new Map([[1,{x:100,y:100}],[2,{x:150,y:100}]]),stage={a:{history:{undo(){undos++;}},toast(){},render(){}},owner:1,pointers:new Map([[1,{}],[2,{}]]),g:{type:'pinch',tapCandidate:true,holdAt:Date.now()-10,startedAt:Date.now()-(scenario==='hold'?1000:10),tapPoints:points},clearMeshHold(){}};Object.setPrototypeOf(stage,StageInput.prototype);
 StageInput.prototype.up.call(stage,{pointerId:1,clientX:scenario==='move'?120:100,clientY:100});assert.equal(undos,0);
 StageInput.prototype.up.call(stage,{pointerId:2,clientX:150,clientY:100});assert.equal(undos,scenario==='tap'?1:0);assert.equal(stage.g,null);
 }
});
test('mesh hold opens the selected colour picker; release cancels its timer',()=>{
 const oldTimeout=globalThis.setTimeout,oldClear=globalThis.clearTimeout,oldDoc=globalThis.document;let callback,delay,cleared=0,opened=0,cancelled=0,styled=0,closePicker,previewCleared=0;
 globalThis.setTimeout=(fn,ms)=>{callback=fn;delay=ms;return 42;};globalThis.clearTimeout=()=>{cleared++;};globalThis.document={addEventListener(){},removeEventListener(){},querySelector:()=>({disabled:false,showPicker(){opened++;}})};
 try{const doc=project(),n=object('rectangle',{mesh:createMesh({x:0,y:0,width:100,height:100})});doc.layers=[n];const stage={a:{doc,selected:[n.id],time:0,pause(){},properties:{flush(){}},dialog(title,body,apply,options){opened++;assert.match(title,/Mesh point 1 colour/);assert.match(body,/applies immediately/);assert.doesNotMatch(body,/Apply colour/);assert.equal(options.modal,false);const hex={value:'#ffffff'},preview={style:{}},palette={insertAdjacentHTML(position,html){assert.equal(position,'beforebegin');assert.match(html,/Last 10 colours/);}};return {classList:{add(name){assert.equal(name,'object-colour-dialog');styled++;}},addEventListener(type,fn,opts){if(type==='close'){assert.equal(opts.once,true);closePicker=fn;}},querySelectorAll(){return [];},querySelector(selector){if(selector==='form')return {addEventListener(){}};if(selector==='.mesh-palette')return palette;if(selector==='[name=colour]')return hex;if(selector==='[data-colour-preview]')return preview;throw Error('Unexpected picker query: '+selector);}};},renderStage(){previewCleared++;},history:{cancel(){cancelled++;}},render(){}},g:{type:'mesh'},owner:1,pointers:new Map([[1,{}]]),clearMeshHold:StageInput.prototype.clearMeshHold};Object.setPrototypeOf(stage,StageInput.prototype);StageInput.prototype.startMeshHold.call(stage,{clientX:100,clientY:100});assert.equal(delay,550);callback();assert.equal(opened,1);assert.equal(cancelled,1);assert.equal(stage.g,null);assert.equal(styled,1);closePicker();assert.equal(previewCleared,1);
 stage.g={type:'mesh'};StageInput.prototype.startMeshHold.call(stage,{clientX:100,clientY:100});StageInput.prototype.up.call(stage,{pointerId:1,clientX:100,clientY:100});assert.ok(cleared>=2);assert.equal(stage.meshHoldTimer,undefined);
 }finally{globalThis.setTimeout=oldTimeout;globalThis.clearTimeout=oldClear;if(oldDoc===undefined)delete globalThis.document;else globalThis.document=oldDoc;}
});

test('a second finger after prior single-finger travel cannot turn pan or handle movement into Undo',()=>{
 const oldDoc=globalThis.document,oldTimeout=globalThis.setTimeout,oldClear=globalThis.clearTimeout;globalThis.document={activeElement:null};globalThis.setTimeout=()=>77;globalThis.clearTimeout=()=>{};
 try{for(const scenario of ['tap','pan','return-to-origin','handle']){let undos=0;const p=project(),a={doc:p,selected:[],tool:'hand',audio:{},properties:{flush(){}},pause(){},renderStage(){},render(){},history:{undo(){undos++;},cancel(){}},toast(){}},stage=Object.assign(Object.create(StageInput.prototype),{a,el:{setPointerCapture(){},hasPointerCapture(){return false;}},pointers:new Map(),view:{zoom:1,x:0,y:0},coord:e=>({x:e.clientX,y:e.clientY}),layout(){}}),event=(id,x)=>({pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:100,preventDefault(){},target:{closest(){return null;}}});stage.down(event(1,100));if(scenario!=='tap'){if(scenario==='handle')stage.g=null;stage.move(event(1,120));if(scenario==='return-to-origin')stage.move(event(1,100));if(scenario==='handle')stage.g={type:'node',edit:true};}stage.down(event(2,160));assert.equal(stage.g.tapCandidate,scenario==='tap');stage.up(event(1,scenario==='return-to-origin'||scenario==='tap'?100:120));stage.up(event(2,160));assert.equal(undos,scenario==='tap'?1:0);assert.equal(stage.g,null);stage.down(event(3,200));assert.equal(stage.ownerTouchMoved,false);stage.down(event(4,250));stage.up(event(3,200));stage.up(event(4,250));assert.equal(undos,scenario==='tap'?2:1);}}
 finally{if(oldDoc===undefined)delete globalThis.document;else globalThis.document=oldDoc;globalThis.setTimeout=oldTimeout;globalThis.clearTimeout=oldClear;}
});
