import test from 'node:test';import assert from 'node:assert/strict';
import {project,object,History,find} from '../dist/document/model.js';
import {setProperty,evaluated} from '../dist/animation/evaluate.js';
import {createMesh} from '../dist/scene/mesh.js';import {editMesh} from '../dist/scene/mesh-edit.js';
import {ImmediateColourSession,bindImmediateColour} from '../dist/ui/immediate-colour.js';
import {showObjectColour,normalColour,objectColourPatch} from '../dist/ui/object-colour.js';
function fixture(mesh=false){const n=object('rectangle',{fill:'#112233',...(mesh?{mesh:createMesh({x:0,y:0,width:100,height:100})}:{})}),doc=project();doc.layers=[n];const recent=[],a={doc,time:2,autoKey:true,ease:'linear',selected:[n.id],properties:{flush(){}},pause(){},renderStage(){},rememberColor:c=>recent.push(c),stage:{finishPath(){}}};a.history=new History(()=>a.doc,v=>a.doc=v);const s=new ImmediateColourSession(a,{ids:[n.id],ownerId:n.id,label:'Colour',apply(c,t){const current=find(a.doc,n.id);if(mesh)editMesh(current,t,m=>{m.points[0].color=c;return m;});else for(const [p,v]of Object.entries(objectColourPatch(current,'fill',c,t)))setProperty(current,p,v,t);}});return {a,n,s,recent};}
test('continuous live colour edits coalesce into one Undo and remember only final colour; closing keeps edits',()=>{const {a,n,s,recent}=fixture();s.update('#334455');assert.equal(evaluated(n,2).fill,'#334455');s.update('#556677');s.update('#778899');assert.equal(a.history.undoStack.length,0);s.close();assert.equal(a.history.undoStack.length,1);assert.deepEqual(recent,['#778899']);assert.equal(evaluated(n,0).fill,'#112233');assert.equal(evaluated(n,2).fill,'#778899');a.history.undo();assert.equal(evaluated(a.doc.layers[0],2).fill,'#112233');a.history.redo();assert.equal(evaluated(a.doc.layers[0],2).fill,'#778899');});
test('each swatch is one undo and identical repeated swatch creates neither undo nor MRU entry',()=>{const {a,s,recent}=fixture();s.update('#334455',true);s.update('#556677',true);s.update('#556677',true);s.close();assert.equal(a.history.undoStack.length,2);assert.deepEqual(recent,['#334455','#556677']);a.history.undo();assert.equal(evaluated(a.doc.layers[0],2).fill,'#334455');});
test('mesh immediate Auto Key preserves earlier colours and other mesh points and preview scopes',()=>{const {a,n,s}=fixture(true);const old=structuredClone(n.mesh);a.appearancePreview=new Map([[n.id,{shadowX:5,motionBlur:{enabled:true}}]]);s.update('#abcdef');s.close();assert.deepEqual(evaluated(n,0).mesh,old);assert.equal(evaluated(n,2).mesh.points[0].color,'#abcdef');assert.deepEqual(evaluated(n,2).mesh.points.slice(1),old.points.slice(1));assert.deepEqual(a.appearancePreview.get(n.id),{shadowX:5,motionBlur:{enabled:true}});a.history.undo();assert.deepEqual(a.doc.layers[0].mesh,old);});
test('stale playhead/selection/project cannot receive another edit or contaminate replacement history',()=>{for(const mode of ['time','selection','project']){const {a,s}=fixture();s.update('#334455');if(mode==='time')a.time=3;if(mode==='selection')a.selected=[];if(mode==='project')a.doc=project();assert.equal(s.update('#ffffff'),false);s.close();assert.equal(a.history.before,null);assert.equal(a.history.undoStack.length,mode==='project'?0:1);}});
test('unrelated history transactions and locked layers are never joined',()=>{const {a,n,s}=fixture();a.history.begin();n.x=80;assert.equal(s.update('#ffffff'),false);assert.equal(n.fill,'#112233');a.history.commit('Move');n.locked=true;assert.equal(s.update('#ffffff'),false);s.close();assert.equal(a.history.undoStack.length,1);});
function element(){const handlers={};return {handlers,value:'',style:{},dataset:{},classList:{add(){},toggle(){}},setAttribute(){},addEventListener(t,fn){(handlers[t]||=[]).push(fn);},emit(t,event={}){for(const fn of handlers[t]||[])fn(event);}};}
test('closing a colour picker clears its shared dialog ownership before another popup uses it',()=>{const oldDoc=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};try{const {a,s}=fixture(),d=element();d.contains=()=>true;d.querySelector=()=>null;d.close=()=>d.emit('close');a.activeColourDialog=d;bindImmediateColour(a,d,s);s.update('#334455');d.close();assert.equal(a.activeColourDialog,null);assert.equal(a.activeColourSession,null);assert.equal(a.history.undoStack.length,1);}finally{globalThis.document=oldDoc;}});
test('object picker hex is valid-only live, Done replaces Apply/Cancel and close keeps one committed edit',()=>{const oldDoc=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};try{const {a,n}=fixture(),hex=element(),native=element(),sample=element(),status=element(),form=element(),d=element();d.querySelector=s=>({'[name=hex]':hex,'[data-colour-native]':native,'[data-colour-sample]':sample,'[data-colour-status]':status,form}[s]);d.querySelectorAll=()=>[];d.contains=()=>true;d.close=()=>d.emit('close');a.dialog=(title,body,apply,options)=>{assert.equal(apply,undefined);assert.equal(options.modal,false);assert.match(body,/Done/);assert.doesNotMatch(body,/Apply colour|Cancel/);return d;};showObjectColour(a);hex.oninput({target:{value:'#badhex'}});assert.equal(a.history.before,null);assert.equal(n.fill,'#112233');hex.value='#abc';hex.oninput({target:hex});assert.equal(hex.value,'#abc');hex.value='#abcd';hex.oninput({target:hex});assert.equal(hex.value,'#abcd');assert.equal(evaluated(n,2).fill,'#aabbcc');native.oninput({target:{value:'#fedcba'}});d.close();assert.equal(a.history.undoStack.length,1);assert.equal(evaluated(n,2).fill,'#fedcba');assert.equal(normalColour('bogus'),null);}finally{globalThis.document=oldDoc;}});
test('outside pointer commits before next canvas transaction; Escape keeps current colour',()=>{const oldDoc=globalThis.document,listeners={};globalThis.document={addEventListener(t,fn){listeners[t]=fn;},removeEventListener(t,fn){if(listeners[t]===fn)delete listeners[t];}};try{for(const action of ['outside','escape']){const {a,s}=fixture(),d=element();d.contains=t=>t===d;d.querySelector=()=>null;d.close=()=>d.emit('close');bindImmediateColour(a,d,s);s.update('#334455');if(action==='outside')listeners.pointerdown({target:{}});else d.emit('keydown',{key:'Escape',preventDefault(){},stopImmediatePropagation(){}});assert.equal(a.history.before,null);assert.equal(a.history.undoStack.length,1);assert.equal(evaluated(a.doc.layers[0],2).fill,'#334455');a.history.run('Move',()=>a.doc.layers[0].x=100);a.history.undo();assert.equal(evaluated(a.doc.layers[0],2).fill,'#334455');assert.equal(a.doc.layers[0].x,0);assert.deepEqual(Object.keys(listeners),[]);}}finally{globalThis.document=oldDoc;}});
