import test from 'node:test';
import assert from 'node:assert/strict';
import {object,project} from '../dist/document/model.js';
import {createMesh} from '../dist/scene/mesh.js';
import {PreviewRenderer,previewMeshContext,sceneSVG,meshRasterSize} from '../dist/renderer/svg.js';
import {FrameRenderer} from '../dist/export/render.js';
let fixtureCount=0;
function fixture(){const p=project();p.width=p.height=100;p.layers=[object('rectangle',{width:100,height:100,mesh:createMesh({x:0,y:0,width:100,height:100},'#12345'+(++fixtureCount).toString(16))})];return p;}
async function fakeCanvas(fn){const saved={document:globalThis.document,Image:globalThis.Image,ImageData:globalThis.ImageData,create:URL.createObjectURL,revoke:URL.revokeObjectURL},sizes=[],blobs=[];globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height});}};globalThis.Image=class{async decode(){}};const canvas=()=>({width:0,height:0,getContext:()=>({putImageData:image=>sizes.push([image.width,image.height]),clearRect(){},fillRect(){},drawImage(){}}),toDataURL:()=>`data:image/png;base64,${Buffer.from('context'+sizes.length).toString('base64')}`});globalThis.document={createElement:()=>canvas(),createElementNS:()=>({childNodes:[],set innerHTML(value){this.markup=value;}})};URL.createObjectURL=blob=>{blobs.push(blob);return 'blob:fixture';};URL.revokeObjectURL=()=>{};try{await fn(sizes,blobs);}finally{globalThis.document=saved.document;globalThis.Image=saved.Image;globalThis.ImageData=saved.ImageData;URL.createObjectURL=saved.create;URL.revokeObjectURL=saved.revoke;}}
test('preview physical scale includes SVG meet aspect ratio, DPR and group transforms',()=>{const p=fixture(),context=previewMeshContext(p,{width:300,height:400},2);assert.equal(context.meshPixelScale,6);assert.equal(context.meshResolution,2048);assert.equal(meshRasterSize(p.layers[0].mesh,[2,0,0,2,0,0],context),1800);assert.equal(previewMeshContext(p,undefined).meshPixelScale,1);});
test('PreviewRenderer passes physical context to artwork rather than staying at 640px',async()=>{await fakeCanvas(async sizes=>{const p=fixture(),svg={childNodes:[],setAttribute(){},getBoundingClientRect:()=>({width:300,height:300})};const renderer=new PreviewRenderer(svg);renderer.render(p,0);assert.deepEqual(sizes,[[512,512]]);assert.match(renderer.cache,/fill="transparent"/);svg.getBoundingClientRect=()=>({width:600,height:600});renderer.render(p,0);assert.deepEqual(sizes,[[512,512],[1024,1024]]);});});
test('sceneSVG accepts optional output-scale context without changing legacy calls',async()=>{await fakeCanvas(async sizes=>{const p=fixture();sceneSVG(p,0);sceneSVG(p,0,undefined,true,{meshPixelScale:6});assert.deepEqual(sizes,[[256,256],[1024,1024]]);});});
test('FrameRenderer uses output dimensions and preserves additive SVG exposure in transparent PNG path',async()=>{await fakeCanvas(async(sizes,blobs)=>{const p=fixture(),n=p.layers[0];n.motionBlur={enabled:true,shutterAngle:180,samples:3};n.tracks.x=[{id:'x0',time:0,value:0,easing:'linear'},{id:'x1',time:1,value:60,easing:'linear'}];const before=JSON.stringify(p);const renderer=new FrameRenderer(p,600,600,true);await renderer.frame(.5);assert.deepEqual(sizes,[[1024,1024]]);const svg=await blobs[0].text();assert.match(svg,/isolation:isolate/);assert.equal((svg.match(/mix-blend-mode:plus-lighter/g)||[]).length,3);assert.doesNotMatch(svg,/<rect width="100%"/);assert.equal(JSON.stringify(p),before);});});
