import test from 'node:test';import assert from 'node:assert/strict';
import {object,project,clone} from '../dist/document/model.js';
import {motionBlurSamples,motionBlurSettings,hasLayerAnimation} from '../dist/animation/motion-blur.js';
import {artwork,sceneSVG,namespaceSVG} from '../dist/renderer/svg.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} differs from ${b}`);
const animated=()=>object('rectangle',{width:100,height:80,motionBlur:{enabled:true,shutterAngle:180,samples:5},tracks:{x:[{id:'first',time:0,value:0,easing:'linear'},{id:'last',time:2,value:200,easing:'linear'}]}});
test('centered shutter is fps-scaled and clamped duplicate samples retain normalized weight',()=>{const n=animated(),before=clone(n),s=motionBlurSamples(n,1,24,2);assert.equal(s.length,5);near(s[0].time,1-1/96);near(s[4].time,1+1/96);assert.equal(s[2].center,true);near(s.reduce((a,b)=>a+b.weight,0),1);assert.deepEqual(motionBlurSamples(n,1,24,2),s);const fast=motionBlurSamples(n,1,60,2);near(fast[4].time-fast[0].time,1/120);assert.deepEqual(n,before);for(const time of [0,2]){const edge=motionBlurSamples(n,time,24,2);assert.equal(edge.length,3);assert.ok(edge.every(v=>v.time>=0&&v.time<=2));near(edge.reduce((a,b)=>a+b.weight,0),1);assert.ok(edge.some(v=>v.time===time&&v.center&&Math.abs(v.weight-.6)<1e-10));}});
test('static and disabled layers bypass blur while nested and block animation qualify',()=>{const n=animated();assert.ok(hasLayerAnimation(n));assert.equal(motionBlurSamples({...n,motionBlur:{enabled:false}},1).length,1);assert.equal(motionBlurSamples({...n,motionBlur:{enabled:true,shutterAngle:0}},1).length,1);const no=object('ellipse',{motionBlur:n.motionBlur});assert.equal(hasLayerAnimation(no),false);assert.equal(motionBlurSamples(no,1).length,1);assert.ok(hasLayerAnimation(object('group',{children:[n]})));assert.ok(hasLayerAnimation(object('rectangle',{blocks:[{tracks:{opacity:[{time:1,value:.5}]}}]})));assert.ok(hasLayerAnimation(object('rectangle',{blockCuts:[{values:{x:50}}]})));assert.deepEqual(motionBlurSettings({motionBlur:{enabled:true,shutterAngle:999,samples:1000}}),{enabled:true,shutterAngle:360,samples:7});});
test('moving vectors render shutter transforms but only center geometry receives hits',()=>{const n=animated(),before=clone(n),s=artwork(n,1,true,false,undefined,{fps:24,duration:2});assert.equal((s.match(/data-blur-time=/g)||[]).length,5);assert.equal((s.match(/data-id=/g)||[]).length,1);assert.ok(s.includes(`data-id="${n.id}"`));assert.equal((s.match(/pointer-events:none/g)||[]).length,4);assert.match(s,/pointer-events:all/);const x=[...s.matchAll(/transform="matrix\(1 0 0 1 ([^ ]+) 0\)"/g)].map(m=>Number(m[1]));assert.equal(x.length,5);assert.ok(Math.min(...x)<100&&Math.max(...x)>100);assert.equal(x.at(-1),100);assert.deepEqual(n,before);n.locked=true;assert.doesNotMatch(artwork(n,1,true),/pointer-events:all/);});
test('group blur suppresses child blur multiplication but unblurred parent permits child blur',()=>{const child=animated(),n=object('group',{children:[child],motionBlur:{enabled:true,shutterAngle:180,samples:7}});let s=artwork(n,1,true);assert.equal((s.match(/data-motion-blur=/g)||[]).length,1);assert.equal((s.match(/data-blur-time=/g)||[]).length,7);assert.ok(s.includes(`data-motion-blur="${n.id}"`));assert.equal((s.match(/data-id=/g)||[]).length,2);n.motionBlur.enabled=false;s=artwork(n,1,true);assert.equal((s.match(/data-motion-blur=/g)||[]).length,1);assert.ok(s.includes(`data-motion-blur="${child.id}"`));assert.equal((s.match(/data-blur-time=/g)||[]).length,5);});
test('temporal clip/mask/shadow/texture definitions have unique matching fragment IDs',()=>{const n=animated();Object.assign(n,{type:'path',nodes:[{x:0,y:0},{x:100,y:0},{x:100,y:80},{x:0,y:80}],closed:true,strokeWidth:8,strokeProfile:'taper-both',lineStyle:'dashed',shadowEnabled:true,texture:{src:'data:image/png;base64,AA==',width:1,height:1,scale:1,x:0,y:0,mode:'cover'}});const s=artwork(n,1,true),ids=[...s.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]),refs=[...s.matchAll(/url\(#([^\)]+)\)/g)].map(m=>m[1]);assert.ok(ids.length>=10);assert.equal(new Set(ids).size,ids.length);assert.ok(refs.every(id=>ids.includes(id)));assert.ok(ids.some(id=>id.includes('shadow-')));assert.ok(ids.some(id=>id.includes('stroke-')));assert.ok(ids.some(id=>id.includes('texture-')));assert.equal((s.match(/data-id=/g)||[]).length,1);const fixed=namespaceSVG('<g data-id="object"><clipPath id="clip"/><use href="#clip"/><g clip-path="url(#clip)"/></g>','copy-');assert.match(fixed,/data-id="object"/);assert.match(fixed,/id="copy-clip"/);assert.match(fixed,/href="#copy-clip"/);assert.match(fixed,/url\(#copy-clip\)/);});
test('SVG export honors project fps and reference exclusion without rasterizing plain vectors',()=>{const p=project();p.fps=60;p.duration=2;const n=animated();p.layers=[n];const s=sceneSVG(p,1,undefined,true);assert.match(s,/<rect width="100"/);assert.doesNotMatch(s,/<canvas|<image|width="100%"/);const ts=[...s.matchAll(/data-blur-time="([^"]+)"/g)].map(m=>Number(m[1]));near(Math.max(...ts)-Math.min(...ts),1/120);n.reference=true;n.exportIncluded=false;assert.doesNotMatch(sceneSVG(p,1),/data-motion-blur/);n.exportIncluded=true;assert.match(sceneSVG(p,1),/data-motion-blur/);});
test('detached motion blur preview never mutates document; constant shutter poses stay opaque',()=>{const n=animated();n.motionBlur.enabled=false;const before=clone(n),preview=new Map([[n.id,{motionBlur:{enabled:true,shutterAngle:360,samples:3}}]]);assert.match(artwork(n,1,true,false,preview),/data-motion-blur/);assert.deepEqual(n,before);n.motionBlur.enabled=true;n.tracks.x[1].value=0;const s=artwork(n,1,true);assert.doesNotMatch(s,/data-motion-blur|data-blur-time/);assert.match(s,/opacity="1"/);});

test('overlapping shutter exposures use isolated additive composition instead of source-over alpha loss',()=>{const n=animated(),s=artwork(n,1);assert.match(s,/style="isolation:isolate"/);assert.equal((s.match(/mix-blend-mode:plus-lighter/g)||[]).length,5);const samples=motionBlurSamples(n,1);assert.ok(Math.abs(samples.reduce((a,b)=>a+b.weight,0)-1)<1e-10);});
