import test from 'node:test';import assert from 'node:assert/strict';
import {MotionBlurPreviewSession,validMotionBlurValue} from '../dist/ui/motion-blur.js';
import {ShadowPreviewSession} from '../dist/ui/layer-menu.js';
import {hasLayerAnimation,motionBlurSettings,motionBlurSamples} from '../dist/animation/motion-blur.js';
import {project,object,History,clone} from '../dist/document/model.js';import {putKey} from '../dist/animation/evaluate.js';
function harness(n=object('rectangle')){let doc=project();doc.layers=[n];let renders=0;const a={get doc(){return doc;},selected:[n.id],time:1,ease:'linear',renderStage(){renders++;},mutate(label,fn){this.history.run(label,fn);}};a.history=new History(()=>doc,next=>doc=next);return {a,get n(){return doc.layers[0];},get renders(){return renders;}};}
test('live motion blur uses detached settings with defaults and never writes document or history',()=>{const h=harness(),before=clone(h.a.doc),s=new MotionBlurPreviewSession(h.a,h.n.id);assert.deepEqual(s.values,{enabled:false,shutterAngle:180,samples:7});s.set('shutterAngle',270);s.set('samples',9);assert.deepEqual(h.a.appearancePreview.get(h.n.id).motionBlur,{enabled:true,shutterAngle:270,samples:9});assert.deepEqual(h.a.doc,before);assert.equal(h.a.history.undoStack.length,0);s.cancel();assert.equal(h.a.appearancePreview.size,0);assert.deepEqual(h.a.doc,before);});
test('Apply creates one undo step and preserves all existing animation keys',()=>{const h=harness();putKey(h.n,'x',0,0);putKey(h.n,'x',2,100);const tracks=clone(h.n.tracks),s=new MotionBlurPreviewSession(h.a,h.n.id);s.set('enabled',true);s.set('samples',11);s.apply();assert.equal(h.a.history.undoStack.length,1);assert.deepEqual(h.n.tracks,tracks);assert.deepEqual(motionBlurSettings(h.n),{enabled:true,shutterAngle:180,samples:11});assert.equal(motionBlurSamples(h.n,1,24,6).length,11);h.a.history.undo();assert.equal(h.n.motionBlur,undefined);assert.deepEqual(h.n.tracks,tracks);});
test('cancel cannot leak into separate canvas history snapshots or later Undo/Redo',()=>{const h=harness(),s=new MotionBlurPreviewSession(h.a,h.n.id);s.set('enabled',true);h.a.mutate('Move',()=>h.n.x=100);s.cancel();h.a.history.undo();h.a.history.redo();assert.equal(h.n.x,100);assert.equal(h.n.motionBlur,undefined);});
test('shadow and motion blur previews merge and cancel independently in either order',()=>{const h=harness(),shadow=new ShadowPreviewSession(h.a,h.n.id),blur=new MotionBlurPreviewSession(h.a,h.n.id);shadow.set('shadowBlur',25);blur.set('shutterAngle',300);shadow.set('shadowX',50);assert.equal(h.a.appearancePreview.get(h.n.id).motionBlur.shutterAngle,300);assert.equal(h.a.appearancePreview.get(h.n.id).shadowX,50);shadow.cancel();assert.deepEqual(Object.keys(h.a.appearancePreview.get(h.n.id)),['motionBlur']);const nextShadow=new ShadowPreviewSession(h.a,h.n.id);nextShadow.set('shadowOpacity',.8);blur.cancel();assert.equal(h.a.appearancePreview.get(h.n.id).shadowOpacity,.8);assert.equal(h.a.appearancePreview.get(h.n.id).motionBlur,undefined);nextShadow.cancel();assert.equal(h.a.appearancePreview.size,0);});
test('applying one feature retains the other detached preview and isolates their undo steps',()=>{const h=harness(),shadow=new ShadowPreviewSession(h.a,h.n.id),blur=new MotionBlurPreviewSession(h.a,h.n.id);shadow.set('shadowBlur',30);blur.set('samples',5);blur.apply();assert.equal(h.a.appearancePreview.get(h.n.id).shadowBlur,30);assert.equal(h.n.shadowBlur,12);shadow.apply();assert.equal(h.a.history.undoStack.length,2);assert.equal(h.a.appearancePreview.size,0);h.a.history.undo();assert.equal(h.n.shadowBlur,12);assert.equal(h.n.motionBlur.samples,5);});
test('animated children enable group blur while static layers retain settings without ghost samples',()=>{const child=object('ellipse');putKey(child,'rotation',0,0);putKey(child,'rotation',2,90);const group=object('group',{children:[child]}),h=harness(group),s=new MotionBlurPreviewSession(h.a,group.id);assert.equal(hasLayerAnimation(group),true);s.set('enabled',true);s.apply();assert.equal(motionBlurSamples(h.n,1,24,6).length,7);const staticLayer=object('rectangle',{motionBlur:{enabled:true,shutterAngle:180,samples:7}});assert.equal(motionBlurSamples(staticLayer,1,24,6).length,1);});
test('locked layers and invalid metadata are rejected; an unchanged Apply creates no history',()=>{const h=harness(),s=new MotionBlurPreviewSession(h.a,h.n.id);for(const [prop,value] of [['samples',4],['shutterAngle',361],['shutterAngle',NaN],['enabled','yes'],['unknown',true]]){assert.equal(validMotionBlurValue(prop,value),false);assert.equal(s.set(prop,value),false);}assert.equal(s.apply(),true);assert.equal(h.a.history.undoStack.length,0);h.n.locked=true;const locked=new MotionBlurPreviewSession(h.a,h.n.id);assert.equal(locked.set('enabled',true),false);assert.equal(locked.apply(),false);});
