import test from 'node:test';
import assert from 'node:assert/strict';
import {animatePathFollow,createPathFollowSession,pathFollowLabels} from '../dist/ui/path-follow.js';
import {attachPathFollow,resolveSceneTransforms} from '../dist/animation/path-follow.js';
import {object,project,History,clone} from '../dist/document/model.js';
import {putKey,evaluated} from '../dist/animation/evaluate.js';
import {validate} from '../dist/document/validate.js';
import {trackNames} from '../dist/timeline/graph.js';
function fixture(){const n=object('rectangle'),guide=object('path',{nodes:[{x:0,y:0},{x:400,y:0}]}),p=project();p.layers=[guide,n];attachPathFollow(p,n.id,guide.id);const a={doc:p,time:1,autoKey:true,ease:'linear',selected:[n.id],properties:{flush(){}}};a.history=new History(()=>a.doc,d=>a.doc=d);return {a,n,p,guide};}
test('path follow edits apply immediately, auto-key earlier pose, coalesce one gesture, and undo',()=>{const {a,n,p}=fixture(),s=createPathFollowSession(a,n.id);s.set('followProgress',30);s.set('followProgress',50);assert.equal(evaluated(n,0).followProgress,0);assert.equal(evaluated(n,1).followProgress,50);assert.equal(resolveSceneTransforms(p,1).get(n.id).world[4],200);s.flush();assert.equal(a.history.undoStack.length,1);s.cancel();validate(p);a.history.undo();assert.equal(evaluated(a.doc.layers[1],1).followProgress,0);a.history.redo();assert.equal(evaluated(a.doc.layers[1],1).followProgress,50);});
test('path session rejects invalid, locked, removed and selection-switched edits',()=>{const {a,n}=fixture(),s=createPathFollowSession(a,n.id);assert.equal(s.set('followNoiseAmount',-1),false);assert.equal(s.set('followNoiseSpeed',NaN),false);n.locked=true;assert.equal(s.set('followProgress',25),false);n.locked=false;a.selected=[];assert.equal(s.set('followProgress',25),false);a.selected=[n.id];delete n.pathFollow;assert.equal(s.set('followProgress',25),false);s.cancel();assert.equal(a.history.undoStack.length,0);});
test('animation button creates uniform travel and holds its endpoint in a longer composition',()=>{const {n,p}=fixture();putKey(n,'opacity',0,.5);putKey(n,'opacity',5,1);const other=clone(n.tracks.opacity),result=animatePathFollow(p,n.id,1,2);assert.equal(result.keys.length,2);assert.equal(evaluated(n,2).followProgress,50);assert.equal(evaluated(n,4).followProgress,100);assert.equal(evaluated(n,6).followProgress,100);assert.deepEqual(n.tracks.opacity,other);assert.equal(p.duration,6);validate(p);});
test('replacing a path travel keeps keys outside the chosen range and preceding frame',()=>{const {n,p}=fixture();putKey(n,'followProgress',0,10,'linear');putKey(n,'followProgress',1,20,'linear');putKey(n,'followProgress',3,70,'linear');putKey(n,'followProgress',5,90,'linear');const first=clone(n.tracks.followProgress[0]),last=clone(n.tracks.followProgress.at(-1)),before=evaluated(n,1-1/p.fps).followProgress;animatePathFollow(p,n.id,1,2);assert.deepEqual(n.tracks.followProgress[0],first);assert.deepEqual(n.tracks.followProgress.at(-1),last);assert.equal(evaluated(n,1-1/p.fps).followProgress,before);assert.equal(evaluated(n,3).followProgress,100);validate(p);});
test('owned block constrains travel duration and retains sibling tracks and base progress',()=>{const {n,p}=fixture();putKey(n,'followProgress',0,35);n.blocks=[{id:'owned',name:'Owned',kind:'animation',start:1,end:4,props:['opacity'],tracks:{opacity:[{id:'opacity-one',time:1,value:.8,easing:'linear'}]}}];const base=clone(n.tracks),opacity=clone(n.blocks[0].tracks.opacity);assert.throws(()=>animatePathFollow(p,n.id,1,4),/fit inside/);const result=animatePathFollow(p,n.id,1,2);assert.equal(result.blockId,'owned');assert.equal(evaluated(n,2).followProgress,50);assert.deepEqual(n.tracks,base);assert.deepEqual(n.blocks[0].tracks.opacity,opacity);assert.ok(n.blocks[0].props.includes('followProgress'));validate(p);});
test('travel extends composition and full-length loop, rejects invalid ranges before mutations',()=>{const {n,p}=fixture();p.playback={start:0,end:6,bpm:120,beatsPerBar:4,measurement:'seconds'};const before=clone(p);assert.throws(()=>animatePathFollow(p,n.id,0,0));assert.throws(()=>animatePathFollow(p,n.id,599,2));assert.deepEqual(p,before);animatePathFollow(p,n.id,5,3);assert.equal(p.duration,8);assert.equal(p.playback.end,8);validate(p);});
test('all follow parameters have readable graph and timeline names',()=>{for(const [prop,label] of Object.entries(pathFollowLabels))assert.equal(trackNames[prop],label);});
