import test from 'node:test';import assert from 'node:assert/strict';
import {StageInput} from '../dist/input/stage.js';import {createRubberHose,rubberHoseGeometry,rubberHoseNodes,updateRubberHose} from '../dist/scene/rubberhose.js';
import {project,object,History,clone} from '../dist/document/model.js';import {validate} from '../dist/document/validate.js';import {evaluated,configureAutoKey,putKey} from '../dist/animation/evaluate.js';import {world,point} from '../dist/scene/matrix.js';import {sceneSVG} from '../dist/renderer/svg.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,a+' differs from '+b);
function fixture(n=object('rectangle')){const a={doc:project(),selected:[n.id],tool:'select',time:0,autoKey:true,ease:'linear',multi:false,nodeEdit:false,snap:false,audio:{},properties:{flush(){}},pause(){},render(){},renderStage(){},toast(){},menus:[],showObjectMenu(id,at){this.menus.push({id,at});}};a.doc.layers=[n];a.history=new History(()=>a.doc,p=>a.doc=p);configureAutoKey(a.doc,true,'linear');const s=Object.create(StageInput.prototype);Object.assign(s,{a,fitScale:1,pointers:new Map(),view:{zoom:1,x:0,y:0},el:{setPointerCapture(){},hasPointerCapture(){return true;},releasePointerCapture(){}},overlay:{innerHTML:''},coord:e=>({x:e.clientX,y:e.clientY})});return s;}
function ev(s,x=40,y=40,extra={}){return {button:0,pointerType:'touch',pointerId:1,clientX:x,clientY:y,preventDefault(){},target:{closest:q=>q==='[data-id]'?{dataset:{id:s.a.selected[0]}}:null},...extra};}
function env(fn){const d=globalThis.document,st=globalThis.setTimeout,ct=globalThis.clearTimeout,timers=new Map();let id=0;globalThis.document={activeElement:null};globalThis.setTimeout=(fn,ms)=>{timers.set(++id,{fn,ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);try{fn({fire(ms){for(const [id,t] of [...timers])if(t.ms===ms){timers.delete(id);t.fn();}},timers});}finally{globalThis.document=d;globalThis.setTimeout=st;globalThis.clearTimeout=ct;}}
test('stationary object hold cancels history and opens exactly one menu without keys or release side effects',()=>env(clock=>{const s=fixture(),before=clone(s.a.doc);s.down(ev(s));s.move(ev(s,47,40));assert.deepEqual(s.a.doc,before);clock.fire(550);assert.deepEqual(s.a.menus,[{id:s.a.selected[0],at:{x:40,y:40}}]);assert.equal(s.a.history.before,null);assert.equal(s.pointers.size,0);s.up(ev(s));s.cancel(ev(s));clock.fire(550);assert.equal(s.a.menus.length,1);assert.equal(s.a.history.undoStack.length,0);assert.deepEqual(s.a.doc,before);}));
test('object drag beyond eight CSS pixels, cancellation, release and second finger disarm the hold',()=>env(clock=>{for(const action of ['move','cancel','up','pinch']){const s=fixture();s.down(ev(s));if(action==='move')s.move(ev(s,49,40));if(action==='cancel')s.cancel(ev(s));if(action==='up')s.up(ev(s));if(action==='pinch')s.down(ev(s,80,40,{pointerId:2}));clock.fire(550);assert.equal(s.a.menus.length,0,action);if(action==='move'){assert.ok(s.a.doc.layers[0].tracks.x.length);s.up(ev(s,49,40));assert.equal(s.a.history.undoStack.length,1);}if(action==='pinch'){s.cancel(ev(s,80,40,{pointerId:2}));s.cancel(ev(s));assert.equal(s.a.history.undoStack.length,0);}}}));
test('pivot target is explicit, 44 CSS pixels and uses evaluated keyed anchor coordinates',()=>{const n=object('rectangle',{anchorX:10,anchorY:20}),s=fixture(n);putKey(n,'anchorX',0,10);putKey(n,'anchorX',2,70);s.a.time=2;s.view.zoom=2;s.fitScale=.5;s.handles();assert.doesNotMatch(s.overlay.innerHTML,/data-handle="anchor"/);s.beginPivotMode();s.handles();assert.match(s.overlay.innerHTML,/data-handle="anchor"><circle cx="70" cy="20" r="22"/);s.endPivotMode();s.handles();assert.doesNotMatch(s.overlay.innerHTML,/data-handle="anchor"/);});
test('keyed pivot dragging on scaled rotated animated objects preserves frame zero and current artwork; reload retains keys',()=>env(()=>{for(const auto of [true,false]){const n=object('rectangle',{x:30,y:50,rotation:35,scaleX:2,scaleY:.6}),s=fixture(n);putKey(n,'rotation',0,35,'linear');putKey(n,'rotation',2,70,'linear');s.a.time=2;s.a.pivotEdit=true;configureAutoKey(s.a.doc,auto,'linear');const zero=world(s.a.doc,n.id,0),current=world(s.a.doc,n.id,2),at=point(current,{x:0,y:0}),e=ev(s,at.x,at.y,{target:{closest:q=>q==='[data-handle]'?{dataset:{handle:'anchor'}}:null}});s.down(e);s.move({...e,clientX:at.x+40,clientY:at.y+25});s.up({...e,clientX:at.x+40,clientY:at.y+25});world(s.a.doc,n.id,0).forEach((v,i)=>near(v,zero[i]));world(s.a.doc,n.id,2).forEach((v,i)=>near(v,current[i]));assert.deepEqual(n.tracks.anchorX.map(k=>k.time),[0,2]);const saved=validate(JSON.parse(JSON.stringify(s.a.doc)));world(saved,n.id,2).forEach((v,i)=>near(v,current[i]));s.a.history.undo();assert.equal(s.a.doc.layers[0].tracks.anchorX,undefined);}}));
test('zoom changes real SVG layout dimensions with translation only and keeps touch coordinates and handle size aligned',()=>env(()=>{const s=fixture(),label={textContent:''};s.a.doc.width=1000;s.a.doc.height=500;s.el={clientWidth:1024,clientHeight:524};s.shell={style:{}};s.overlay={innerHTML:'',setAttribute(){}};globalThis.document.querySelector=()=>label;s.view={zoom:2,x:30,y:-10};s.layout();assert.equal(s.shell.style.width,'2000px');assert.equal(s.shell.style.height,'1000px');assert.equal(s.shell.style.transform,'translate(30px,-10px)');assert.equal(label.textContent,'200%');s.svg={getBoundingClientRect:()=>({left:-470,top:-250,width:2000,height:1000})};const p=StageInput.prototype.coord.call(s,{clientX:530,clientY:250});near(p.x,500);near(p.y,250);assert.match(s.overlay.innerHTML,/r="11"/);}));
test('rubber hose remains a curved round-ended SVG path with compatible AutoKey bend and width edits and undo',()=>{const n=createRubberHose({ik:false}),s=fixture(n),initial=clone(n.nodes);s.a.time=2;s.a.history.run('Bend limb',()=>updateRubberHose(n,{bend:{x:100,y:90},width:32},2));assert.equal(n.type,'path');assert.deepEqual(n.tracks.nodes.map(k=>k.time),[0,2]);assert.deepEqual(evaluated(n,0).nodes,initial);assert.deepEqual(rubberHoseGeometry(n,2).bend,{x:100,y:90});near(evaluated(n,0).strokeWidth,24);near(evaluated(n,2).strokeWidth,32);const nodes=evaluated(n,2).nodes;near((nodes[1].x-nodes[1].in.x)*(nodes[1].out.y-nodes[1].y)-(nodes[1].y-nodes[1].in.y)*(nodes[1].out.x-nodes[1].x),0);assert.match(sceneSVG(s.a.doc,2),/C/);assert.match(sceneSVG(s.a.doc,2),/stroke-linecap="round"/);validate(JSON.parse(JSON.stringify(s.a.doc)));s.a.history.undo();assert.deepEqual(s.a.doc.layers[0].nodes,initial);assert.throws(()=>rubberHoseNodes({x:NaN,y:0},{x:1,y:2},{x:3,y:4}));assert.throws(()=>updateRubberHose(n,{width:-1},2));});
test('rubber hose anchor touch drag recalculates curvature without drift and preserves the initial keyed pose',()=>env(()=>{const n=createRubberHose({ik:false}),s=fixture(n),original=clone(n.nodes);s.a.tool='direct';s.a.nodeEdit=true;s.a.time=2;s.a.activeNode=1;s.visibleNodes=[0,1,2];const e=ev(s,90,60,{target:{closest:q=>q==='[data-node]'?{dataset:{node:'1'}}:null}});s.down(e);s.move({...e,clientX:120,clientY:110});s.move({...e,clientX:120,clientY:110});s.up({...e,clientX:120,clientY:110});assert.deepEqual(rubberHoseGeometry(n,2).bend,{x:120,y:110});assert.deepEqual(evaluated(n,0).nodes,original);assert.equal(n.tracks.nodes.length,2);assert.equal(s.a.history.undoStack.length,1);}));
test('IK posing shows all three point targets even at small zoom and hides tangent handles; free curves retain them',()=>{
 const n=createRubberHose(),s=fixture(n);s.a.tool='direct';s.a.nodeEdit=true;s.a.activeNode=1;s.view.zoom=.05;s.handles();assert.deepEqual(s.visibleNodes,[0,1,2]);assert.equal((s.overlay.innerHTML.match(/data-node=/g)||[]).length,3);assert.doesNotMatch(s.overlay.innerHTML,/data-side=/);assert.doesNotMatch(s.overlay.innerHTML,/data-handle="resize/);
 n.rubberhoseRig.enabled=false;s.view.zoom=1;s.handles();assert.match(s.overlay.innerHTML,/data-side="in"/);assert.match(s.overlay.innerHTML,/data-side="out"/);
});
test('stale IK tangent targets do not begin history, move geometry or add keys',()=>env(()=>{
 const n=createRubberHose(),s=fixture(n),before=clone(s.a.doc);s.a.tool='direct';s.a.nodeEdit=true;s.a.time=2;const e=ev(s,55,45,{target:{closest:q=>q==='[data-node]'?{dataset:{node:'1',side:'out'}}:null}});s.down(e);assert.equal(s.a.history.before,null);assert.equal(s.g,undefined);s.move({...e,clientX:90,clientY:80});s.up({...e,clientX:90,clientY:80});assert.deepEqual(s.a.doc,before);assert.equal(s.a.history.undoStack.length,0);
}));

test('Shapes tools stationary hold opens Delete-capable object menu without creating artwork or keys',()=>env(clock=>{for(const tool of ['rect','ellipse','triangle','polygon','star','line','text']){const s=fixture();s.a.tool=tool;s.a.time=2;const back=s.a.doc.layers[0],front=object('ellipse');s.a.doc.layers.push(front);const before=clone(s.a.doc),e=ev(s,40,40,{target:{closest:q=>q==='[data-id]'?{dataset:{id:front.id}}:null}});s.down(e);assert.equal(s.g.type,'move');assert.deepEqual(s.a.selected,[front.id]);s.move({...e,clientX:47});clock.fire(550);assert.deepEqual(s.a.menus,[{id:front.id,at:{x:40,y:40}}]);assert.deepEqual(s.a.doc,before);assert.equal(s.a.history.before,null);s.up(e);assert.equal(s.a.history.undoStack.length,0);assert.equal(s.a.doc.layers[0].id,back.id);assert.equal(s.a.doc.layers.length,2);}}));
test('Shapes hold disarms on drag, lift, cancel, second finger and tool change',()=>env(clock=>{for(const action of ['move','up','cancel','pinch','tool']){const s=fixture();s.a.tool='rect';s.down(ev(s));if(action==='move')s.move(ev(s,49));if(action==='up')s.up(ev(s));if(action==='cancel')s.cancel(ev(s));if(action==='pinch')s.down(ev(s,80,40,{pointerId:2}));if(action==='tool')s.a.tool='pencil';clock.fire(550);assert.equal(s.a.menus.length,0,action);assert.equal(s.a.doc.layers.length,1);s.cancel(ev(s));}}));
test('drawing Pen and Pencil on existing artwork stays drawing and cannot open object hold',()=>env(clock=>{for(const tool of ['path','pencil']){const s=fixture();s.a.tool=tool;s.a.drawColor='#112233';s.down(ev(s));assert.equal(s.g.type,tool==='path'?'pen-node':'draw');clock.fire(550);assert.equal(s.a.menus.length,0);s.cancel(ev(s));assert.equal(s.a.doc.layers.length,1);}}));
