import test from 'node:test';import assert from 'node:assert/strict';
import {Properties,propertyTabs,editorSectionTab,propertyPanels,propertyKeyState,propertyKeyButton,displayedSize} from '../dist/ui/properties.js';
import {project,object,History,clone} from '../dist/document/model.js';
import {putKey,evaluated} from '../dist/animation/evaluate.js';
import {sceneSVG} from '../dist/renderer/svg.js';
import {localBounds} from '../dist/scene/matrix.js';
const input=(key,value,type='number')=>({target:{dataset:{prop:key},tagName:'INPUT',type,value:String(value),hasAttribute(){return false;}}});
function harness(n,time=0){let doc=project();doc.layers=[n];let previews=0;const number={type:'number',value:String(n.strokeWidth)},slider={type:'range',value:String(n.strokeWidth),max:'100'},status={textContent:''},properties=Object.create(Properties.prototype);properties.app={get doc(){return doc;},selected:[n.id],time,drawColor:'#123456',pause(){},rememberColor(){},renderStage(){previews++;},mutate(label,fn){properties.flush();this.history.run(label,fn);}};properties.app.history=new History(()=>doc,p=>doc=p);properties.el={querySelectorAll(selector){return selector==='[data-prop="strokeWidth"]'?[number,slider]:[];},querySelector(){return status;},closest(){return null;}};return {properties,get n(){return doc.layers[0];},get doc(){return doc;},number,slider,status,get previews(){return previews;}};}

test('stable tabs put shape, mesh, style and alignment in predictable sections',()=>{assert.deepEqual(propertyTabs.map(([id])=>id),['transform','style','shape','animate']);assert.equal(editorSectionTab('Object selection'),'transform');assert.equal(editorSectionTab('Align selection'),'transform');assert.equal(editorSectionTab('Line style & width profile'),'style');assert.equal(editorSectionTab('Mesh shading'),'style');for(const heading of ['','Polygon shape','Path points · 2'])assert.equal(editorSectionTab(heading),'shape');});
test('Style exposes synced line controls, Shape preserves content editing, and groups keep applicable capabilities',()=>{const n=object('text'),a={time:0,drawColor:'#123456',constrain:false,fromCenter:false};let panels=propertyPanels(a,n);assert.match(panels.style,/data-width-slider/);assert.match(panels.style,/data-prop="strokeWidth" type="number"/);assert.match(panels.shape,/data-prop="text"/);assert.match(panels.shape,/data-prop="font"/);assert.match(panels.animate,/Auto Key/);const g=object('group',{children:[object('rectangle')]});panels=propertyPanels(a,g);assert.match(panels.style,/Select contents/);assert.doesNotMatch(panels.style,/data-prop="fill"|data-width-slider/);assert.match(panels.shape,/data-edit="contents"/);assert.match(panels.animate,/data-key="scaleX"/);assert.doesNotMatch(panels.animate,/data-key="fill"/);});
test('Stroke width slider updates numeric geometry and preview, enables a missing stroke, and makes one undo step',()=>{const h=harness(object('path',{fill:'none',stroke:'none',strokeWidth:0,nodes:[{x:0,y:0},{x:100,y:60}]}));h.properties.input(input('strokeWidth',12.5,'range'));h.properties.input(input('strokeWidth',18,'range'));assert.equal(h.n.strokeWidth,18);assert.equal(typeof h.n.strokeWidth,'number');assert.equal(h.n.stroke,'#123456');assert.equal(Number(h.number.value),18);assert.equal(Number(h.slider.value),18);assert.match(h.status.textContent,/visible/);assert.equal(h.previews,2);assert.equal(h.properties.app.history.undoStack.length,0);assert.match(sceneSVG(h.doc,0),/stroke-width="18"/);h.properties.flush();assert.equal(h.properties.app.history.undoStack.length,1);h.properties.app.history.undo();assert.equal(h.n.strokeWidth,0);assert.equal(h.n.stroke,'none');});
test('numeric width edits synchronize the slider beyond its initial range and preserve existing keyed widths',()=>{const n=object('rectangle',{strokeWidth:2});putKey(n,'strokeWidth',0,2,'linear');putKey(n,'strokeWidth',2,8);const h=harness(n,1);h.properties.input(input('strokeWidth',150));assert.equal(Number(h.slider.max),150);assert.equal(Number(h.slider.value),150);assert.equal(evaluated(h.n,1).strokeWidth,150);assert.equal(h.n.tracks.strokeWidth[0].value,2);assert.equal(h.n.tracks.strokeWidth.at(-1).value,8);h.properties.flush();assert.equal(h.properties.app.history.undoStack.length,1);h.properties.app.history.undo();assert.equal(evaluated(h.n,1).strokeWidth,5);});
test('group Width scales the whole group instead of changing unused container dimensions',()=>{const children=[object('rectangle',{x:20,width:50}),object('ellipse',{x:100,width:40})],n=object('group',{children,scaleX:-1}),before=clone(children),h=harness(n),width=localBounds(n).width;h.properties.input(input('width',width*2));assert.equal(h.n.scaleX,-2);assert.equal(displayedSize(h.n,0,'width'),width*2);assert.deepEqual(h.n.children,before);assert.equal(h.n.width,180);h.properties.flush();h.properties.app.history.undo();assert.equal(h.n.scaleX,-1);});
test('tab switches commit the pending field edit and locked parents block width changes',()=>{const h=harness(object('rectangle'));h.properties.input(input('strokeWidth',8,'range'));let forced=false;h.properties.render=value=>forced=value;h.properties.selectTab('style');assert.equal(h.properties.tab,'style');assert.equal(forced,true);assert.equal(h.properties.app.history.undoStack.length,1);const child=object('rectangle'),group=object('group',{locked:true,children:[child]});h.doc.layers=[group];h.properties.app.selected=[child.id];h.properties.input(input('strokeWidth',20,'range'));assert.equal(child.strokeWidth,0);assert.equal(h.properties.app.history.undoStack.length,1);});
test('round key buttons distinguish animation off, enabled, and a current block key',()=>{const n=object('rectangle');assert.deepEqual(propertyKeyState(n,'x',1),{enabled:false,current:false});assert.match(propertyKeyButton(n,'x','Position X',1),/aria-pressed="false"/);putKey(n,'x',0,0);assert.deepEqual(propertyKeyState(n,'x',1),{enabled:true,current:false});n.blocks=[{id:'b',start:1,end:3,props:['x'],tracks:{x:[{id:'k',time:2,value:40,easing:'linear'}]}}];assert.deepEqual(propertyKeyState(n,'x',2),{enabled:true,current:true});assert.match(propertyKeyButton(n,'x','Position X',2),/keyframe here/);assert.match(propertyKeyButton(n,'x','Position X',2),/at-key/);});
