import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {MotionRecorder} from '../dist/animation/record-motion.js';import {project,object,History,clone} from '../dist/document/model.js';
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
// Exercise the actual App method without constructing the browser-only workspace.
const saveMethod=source.slice(source.indexOf('async save(){'),source.indexOf('\nrenderStage(){'));
function harness(){let doc=project(),clock=0;const n=object('rectangle');doc.layers=[n];const timers=new Map(),saved=[];let timerId=0,flushes=0;const a={get doc(){return doc;},assets:new Map(),time:2,autoKey:false,ease:'linear',tool:'select',recordMotionArmed:true,properties:{flush(){flushes++;}},stage:{finishPath(){}},audio:{},pause(){},render(){},renderStage(){},safe:fn=>Promise.resolve(fn()),store:{async save(doc){saved.push(clone(doc));}}};a.history=new History(()=>doc,next=>doc=next);a.save=new Function('$','clearTimeout','setTimeout','return ({'+saveMethod+'}).save;')(()=>({textContent:'',title:''}),id=>timers.delete(id),(fn,ms)=>{assert.equal(ms,250);timers.set(++timerId,fn);return timerId;});a.motionRecorder=new MotionRecorder(a,{now:()=>clock,raf:()=>17,cancelRaf(){}});a.history.begin();const g={type:'move',started:true,edit:true,items:[{id:n.id,v:clone(n)}]};a.motionRecorder.begin(g);a.motionRecorder.pose([{id:n.id,x:120,y:90}]);clock=100;a.motionRecorder.tick();return {a,saved,timers,get flushes(){return flushes;}};}
test('App save defers an active take and deferred autosave persists only restored document after cancellation',async()=>{const h=harness();await h.a.save();assert.equal(h.saved.length,0);assert.equal(h.timers.size,1);assert.equal(h.flushes,0);h.a.motionRecorder.cancel({render:false});const callback=[...h.timers.values()][0];await callback();assert.equal(h.saved.length,1);assert.deepEqual(h.saved[0].layers[0].tracks,{});assert.equal(h.a.autoKey,false);assert.equal(h.a.history.undoStack.length,0);});
test('deferred save persists the completed motion take after release with its one history step',async()=>{const h=harness();await h.a.save();h.a.motionRecorder.finish();h.a.history.commit('Record motion');await [...h.timers.values()][0]();assert.equal(h.saved.length,1);assert.ok(h.saved[0].layers[0].tracks.x.length>1);assert.equal(h.saved[0].layers[0].tracks.x.at(-1).value,120);assert.equal(h.a.history.undoStack.length,1);});
test('root hidden-tab handler cancels before it saves so partial take cannot survive reload',async()=>{const h=harness(),start=source.indexOf("document.addEventListener('visibilitychange',()=>"),end=source.indexOf('\nkeyboard(e)',start);assert.ok(start>=0&&end>start);const binding=source.slice(start,end).replace(/}\s*$/,'');let pending,listener;h.a.safe=fn=>pending=Promise.resolve(fn());new Function('document',binding).call(h.a,{hidden:true,addEventListener(name,fn){listener=fn;}});listener();await pending;assert.equal(h.a.motionRecorder.active,false);assert.equal(h.a.time,2);assert.equal(h.saved.length,1);assert.deepEqual(h.saved[0].layers[0].tracks,{});assert.equal(h.a.autoKey,false);});
