import test from 'node:test';import assert from 'node:assert/strict';
import {ShadowPreviewSession,validShadowValue} from '../dist/ui/layer-menu.js';
import {project,object,History,clone} from '../dist/document/model.js';import {putKey,evaluated,configureAutoKey} from '../dist/animation/evaluate.js';import {sceneSVG} from '../dist/renderer/svg.js';
function harness(){let doc=project();const n=object('rectangle');doc.layers=[n];let renders=0;const a={get doc(){return doc;},selected:[n.id],time:1,ease:'linear',renderStage(){renders++;},mutate(label,fn){this.history.run(label,fn);}};a.history=new History(()=>doc,next=>doc=next);return {a,get n(){return doc.layers[0];},get renders(){return renders;}};}
test('live shadow preview is detached from document/history and adjusting values enables visible Preview',()=>{const h=harness(),before=clone(h.a.doc),s=new ShadowPreviewSession(h.a,h.n.id);assert.ok(s.set('shadowX',50));assert.equal(h.a.appearancePreview.get(h.n.id).shadowX,50);assert.equal(h.a.appearancePreview.get(h.n.id).shadowEnabled,true);assert.deepEqual(h.a.doc,before);assert.equal(h.a.history.undoStack.length,0);s.set('shadowEnabled',false);assert.equal(h.a.appearancePreview.get(h.n.id).shadowEnabled,false);s.cancel();assert.equal(h.a.appearancePreview.size,0);assert.deepEqual(h.a.doc,before);assert.equal(h.renders,1);});
test('cancel cannot contaminate another canvas action or resurrect preview during Undo/Redo',()=>{const h=harness(),s=new ShadowPreviewSession(h.a,h.n.id);s.set('shadowBlur',60);h.a.mutate('Move artwork',()=>h.n.x=200);s.cancel();assert.equal(h.n.x,200);assert.equal(h.n.shadowBlur,12);h.a.history.undo();assert.equal(h.n.x,0);h.a.history.redo();assert.equal(h.n.x,200);assert.equal(h.n.shadowBlur,12);assert.equal(h.n.shadowEnabled,false);});
test('Apply commits only changed properties in one undo step and preserves neighbouring animated parameters',()=>{const h=harness();putKey(h.n,'shadowX',0,10,'linear');putKey(h.n,'shadowX',2,30,'linear');putKey(h.n,'shadowY',0,20,'linear');putKey(h.n,'shadowY',2,40,'linear');const y=clone(h.n.tracks.shadowY),s=new ShadowPreviewSession(h.a,h.n.id);assert.equal(s.values.shadowX,20);assert.equal(s.values.shadowY,30);s.set('shadowX',100);s.set('shadowOpacity',.8);s.apply();assert.equal(h.a.history.undoStack.length,1);assert.equal(h.a.appearancePreview.size,0);assert.equal(evaluated(h.n,1).shadowX,100);assert.deepEqual(h.n.tracks.shadowY,y);assert.equal(h.n.tracks.shadowX[0].value,10);assert.equal(h.n.tracks.shadowX.at(-1).value,30);assert.match(sceneSVG(h.a.doc,1),/dx="100" dy="30"/);h.a.history.undo();assert.equal(evaluated(h.n,1).shadowX,20);assert.equal(h.n.shadowEnabled,false);});
test('undirty controls follow playhead evaluation while dirty detached controls stay stable',()=>{const h=harness();putKey(h.n,'shadowX',0,10,'linear');putKey(h.n,'shadowX',2,30,'linear');const s=new ShadowPreviewSession(h.a,h.n.id);h.a.time=2;s.refresh();assert.equal(s.values.shadowX,30);s.set('shadowX',70);h.a.time=0;s.refresh();assert.equal(s.values.shadowX,70);s.apply();assert.equal(evaluated(h.n,0).shadowX,70);});
test('Animate creates independent shadow tracks with starting poses and respects inherited locks',()=>{const h=harness();configureAutoKey(h.a.doc,true,'linear');const s=new ShadowPreviewSession(h.a,h.n.id);s.set('shadowX',80);s.apply(true);assert.equal(h.a.history.undoStack.length,1);assert.equal(h.n.tracks.shadowX[0].value,12);assert.equal(h.n.tracks.shadowX.at(-1).value,80);assert.ok(h.n.tracks.shadowY.length);const locked=object('group',{locked:true,children:[h.n]});h.a.doc.layers=[locked];const p=new ShadowPreviewSession(h.a,h.n.id);assert.equal(p.set('shadowX',200),false);assert.equal(p.apply(),false);});
test('invalid shadow values are rejected without modifying preview or exports',()=>{const h=harness(),s=new ShadowPreviewSession(h.a,h.n.id);for(const [prop,value] of [['shadowBlur',-1],['shadowOpacity',2],['shadowX',NaN],['shadowColor','url(x)'],['shadowEnabled','yes']]){assert.equal(validShadowValue(prop,value),false);assert.equal(s.set(prop,value),false);}assert.equal(h.a.appearancePreview.size,0);assert.equal(s.apply(),true);assert.equal(h.a.history.undoStack.length,0);});

test('group shadow previews cancel cleanly and animated Apply affects group alpha with one undo',()=>{const h=harness(),child=h.n,g=object('group',{children:[child],shadowEnabled:true});h.a.doc.layers=[g];h.a.selected=[g.id];putKey(g,'shadowX',0,10,'linear');putKey(g,'shadowX',2,30,'linear');const before=clone(h.a.doc),s=new ShadowPreviewSession(h.a,g.id);assert.equal(s.values.shadowX,20);s.set('shadowBlur',80);s.cancel();assert.deepEqual(h.a.doc,before);assert.equal(h.a.history.undoStack.length,0);const next=new ShadowPreviewSession(h.a,g.id);next.set('shadowX',140);next.apply(true);assert.equal(h.a.history.undoStack.length,1);assert.equal(evaluated(g,1).shadowX,140);assert.deepEqual(child.tracks,{});assert.match(sceneSVG(h.a.doc,1),new RegExp('filter="url\\(#shadow-'+g.id+'\\)"'));h.a.history.undo();assert.deepEqual(h.a.doc,before);h.a.history.redo();assert.equal(evaluated(h.a.doc.layers[0],1).shadowX,140);});
