import test from 'node:test';import assert from 'node:assert/strict';
import {studioMenuDefinitions,studioLayerRows,selectStudioLayer,studioLayerAction,studioCommand} from '../dist/ui/studio-menus.js';
import {project,object,History,clone} from '../dist/document/model.js';
function harness(){let doc=project();const first=object('rectangle',{name:'Back'}),child=object('ellipse',{name:'Child'}),group=object('group',{name:'Group',children:[child]}),top=object('rectangle',{name:'Front'});doc.layers=[first,group,top];const a={get doc(){return doc;},selected:[top.id],keyIds:new Set(['key']),properties:{flush(){}},stage:{finishPath(){}},tool:'select',render(){},mutate(label,fn){this.history.run(label,fn);}};a.history=new History(()=>doc,next=>doc=next);return {a,first,child,group,top};}
test('traditional menus stay in three predictable labelled groups and reuse existing commands',()=>{assert.deepEqual(studioMenuDefinitions.map(([name])=>name),['File','Edit','Options']);assert.ok(studioMenuDefinitions[0][1].some(([,id])=>id==='export-project'));assert.ok(studioMenuDefinitions[1][1].some(([,id])=>id==='group'));assert.ok(studioMenuDefinitions[2][1].some(([,id])=>id==='studio-layers'));const previous=globalThis.document;let clicks=0;globalThis.document={getElementById(){return {disabled:false,click(){clicks++;}};}};try{studioCommand({},'group');assert.equal(clicks,1);globalThis.document.getElementById=()=>({disabled:true,click(){clicks++;}});studioCommand({},'group');assert.equal(clicks,1);}finally{globalThis.document=previous;}});
test('Layers follows visual stacking, indents children and collapses groups without changing scene data',()=>{const {a,first,child,group,top}=harness(),before=clone(a.doc);assert.deepEqual(studioLayerRows(a.doc).map(({n,depth})=>[n.id,depth]),[[top.id,0],[group.id,0],[child.id,1],[first.id,0]]);assert.deepEqual(studioLayerRows(a.doc,new Set([group.id])).map(({n})=>n.id),[top.id,group.id,first.id]);assert.deepEqual(a.doc,before);});
test('single and multiple layer selection clear key selection and preserve Direct edit mode',()=>{const {a,first,top}=harness();a.tool='direct';selectStudioLayer(a,first.id);assert.deepEqual(a.selected,[first.id]);assert.equal(a.keyIds.size,0);assert.equal(a.nodeEdit,true);selectStudioLayer(a,top.id,true);assert.deepEqual(a.selected,[first.id,top.id]);selectStudioLayer(a,first.id,true);assert.deepEqual(a.selected,[top.id]);selectStudioLayer(a,'missing');assert.deepEqual(a.selected,[top.id]);});
test('rename, visibility and locks produce undoable edits with inherited lock guards',()=>{const {a,child,group,top}=harness();assert.ok(studioLayerAction(a,'rename',top.id,'  Balloon  '));assert.equal(top.name,'Balloon');assert.equal(a.history.undoStack.length,1);a.history.undo();assert.equal(a.doc.layers.at(-1).name,'Front');assert.ok(studioLayerAction(a,'visible',top.id));assert.equal(a.doc.layers.at(-1).visible,false);studioLayerAction(a,'lock',group.id);assert.equal(studioLayerAction(a,'rename',child.id,'Hidden rename'),false);assert.equal(studioLayerAction(a,'lock',child.id),false);assert.equal(studioLayerAction(a,'lower',child.id),false);assert.ok(studioLayerAction(a,'lock',group.id));assert.ok(studioLayerAction(a,'rename',child.id,'Petal'));assert.equal(a.doc.layers[1].children[0].name,'Petal');assert.equal(studioLayerAction(a,'rename',child.id,'   '),false);});
test('Raise and Lower move only among siblings and preserve object and animation values',()=>{const {a,first,child,group,top}=harness();top.tracks={x:[{id:'k',time:2,value:100,easing:'linear'}]};const before=clone(top);assert.ok(studioLayerAction(a,'lower',top.id));assert.deepEqual(a.doc.layers.map(n=>n.id),[first.id,top.id,group.id]);assert.deepEqual(top,before);assert.equal(studioLayerAction(a,'raise',child.id),false);assert.ok(studioLayerAction(a,'raise',top.id));assert.deepEqual(a.doc.layers.map(n=>n.id),[first.id,group.id,top.id]);assert.equal(studioLayerAction(a,'raise',top.id),false);a.history.undo();assert.deepEqual(a.doc.layers.map(n=>n.id),[first.id,top.id,group.id]);});
test('object clipboard and video/rubber-hose commands use root hooks and guard empty or locked selection',()=>{const {a,top}=harness();const calls=[];a.copyObjects=()=>calls.push('copy');a.cutObjects=()=>calls.push('cut');a.pasteObjects=()=>calls.push('paste');a.addRubberHose=()=>calls.push('hose');a.showVideoReference=()=>calls.push('video');studioCommand(a,'studio-copy');studioCommand(a,'studio-cut');studioCommand(a,'studio-paste');assert.deepEqual(calls,['copy','cut']);a.objectClipboard=[{}];studioCommand(a,'studio-paste');studioCommand(a,'studio-rubber-hose');studioCommand(a,'studio-video-reference');assert.deepEqual(calls,['copy','cut','paste','hose','video']);top.locked=true;studioCommand(a,'studio-cut');studioCommand(a,'studio-copy');assert.equal(calls.length,6);assert.equal(calls.at(-1),'copy');});
