import test from 'node:test';
import assert from 'node:assert/strict';
import {object,project} from '../dist/document/model.js';
import {navigationKeys,adjacentKeyTime,selectedBlockRange,timelineViewPlan,nextPosePlan,frameTimelineRange,advanceNextPose,stepTimelineKey,revealTimelineRow} from '../dist/ui/timeline-navigation.js';
const key=(id,time)=>({id,time,value:time,easing:'linear'});
function fixture(){const p=project(),n=object('rectangle',{id:'a',tracks:{x:[key('a0',0),key('a1',1),key('a2',2),key('a4',4)],y:[key('y3',3)]}});p.layers=[n];return {p,n};}
test('steps all selected layer properties, skips current key and does not mutate document',()=>{const {p}=fixture(),before=JSON.stringify(p),state={selected:['a']};assert.equal(adjacentKeyTime(p,state,1,1),2);assert.equal(adjacentKeyTime(p,state,1,-1),0);assert.equal(adjacentKeyTime(p,state,0,-1),null);assert.equal(adjacentKeyTime(p,state,6,1),null);assert.equal(JSON.stringify(p),before);});
test('selected key identifies its whole property track, no unrelated properties',()=>{const {p}=fixture(),state={selected:['a'],keyIds:new Set(['a1'])};assert.equal(adjacentKeyTime(p,state,2,1),4);assert.ok(navigationKeys(p,state).every(k=>k.property==='x'));});
test('selected group traverses children but references and unrelated nodes are excluded',()=>{const {p,n}=fixture(),ref=object('image',{id:'ref',reference:true,tracks:{x:[key('r',.5)]}}),other=object('ellipse',{id:'other',tracks:{x:[key('o',.7)]}});p.layers=[object('group',{id:'g',children:[n,ref]}),other];assert.deepEqual(navigationKeys(p,{selected:['g']}).map(k=>k.id),['a0','a1','a2','y3','a4']);assert.equal(navigationKeys(p).length,0);});
test('block track keys outside trimmed range and overwritten base keys are excluded',()=>{const {p,n}=fixture();n.blocks=[{id:'b',start:.5,end:2.5,props:['x'],tracks:{x:[key('b0',0),key('b1',1.5),key('b2',2.5),key('b3',3)]}}];assert.deepEqual(navigationKeys(p,{selected:['a']}).map(k=>k.id),['a0','b1','b2','y3','a4']);});
test('selected block isolates its track and explicit key selection takes precedence',()=>{const {p,n}=fixture();n.blocks=[{id:'b',start:1,end:3,props:['x'],tracks:{x:[key('b1',1),key('b2',2.5),key('b3',3)]}}];const state={selected:['a'],blockSelection:{object:'a',id:'b'}};assert.deepEqual(navigationKeys(p,state).map(k=>k.id),['b1','b2','b3']);assert.deepEqual(navigationKeys(p,{...state,keyIds:new Set(['a1'])}).map(k=>k.id),['a0','a1','a2','a4']);});
test('synthetic base block navigation retains base track keys and app reads timeline block selection',()=>{const a=app();a.timeline.blockSelection={object:'a',id:'animation-a'};assert.equal(stepTimelineKey(a,1),2);assert.deepEqual(navigationKeys(a.doc,{selected:['a'],blockSelection:a.timeline.blockSelection}).map(k=>k.id),['a0','a1','a2','y3','a4']);});
test('overlapping block ownership follows last block and cuts hide base animation',()=>{const {p,n}=fixture();n.blockCuts=[{start:0,end:.5,values:{x:0}}];n.blocks=[{id:'b',start:1,end:3,tracks:{x:[key('b',2)]}},{id:'c',start:1,end:3,tracks:{x:[key('c',2.2)]}}];assert.deepEqual(navigationKeys(p,{selected:['a']}).map(k=>k.id),['c','y3','a4']);});
test('focus range supports synthetic animation, references and trimmed audio',()=>{const {p}=fixture();assert.deepEqual(selectedBlockRange(p,{object:'a',id:'animation-a'}),{start:0,end:4});p.audio={assetId:'sound',offset:2,trimStart:1,trimEnd:3};assert.deepEqual(selectedBlockRange(p,{object:'audio',id:'audio-sound'}),{start:2,end:4});assert.equal(selectedBlockRange(p,{object:'missing',id:'x'}),null);});
test('Fit fits full lane on narrow screens and focus centers in a zoomed view',()=>{const fit=timelineViewPlan({duration:6,viewportWidth:420,labelWidth:244,baseWidth:500});assert.ok(500*fit.zoom<=176);assert.equal(fit.scrollLeft,0);const focus=timelineViewPlan({duration:100,viewportWidth:1000,labelWidth:200,baseWidth:800,start:40,end:60});assert.ok(Math.abs((50/100*800*focus.zoom-focus.scrollLeft)-400)<1e-8);assert.equal(timelineViewPlan({duration:6,viewportWidth:0}),null);});
test('Next pose frame grid, duration extension and ten-minute bound',()=>{for(const fps of [12,24,25,30,60]){const p={fps,duration:6};const plan=nextPosePlan(p,5.53);assert.ok(Math.abs(plan.time*fps-Math.round(plan.time*fps))<1e-8);assert.equal(plan.duration,plan.time);assert.equal(nextPosePlan(p,599.8).time,600);assert.equal(p.duration,6);}});
function app(){const {p}=fixture();const a={doc:p,time:1,selected:['a'],keyIds:new Set(),autoKey:false,seek(t){this.time=t;},toast(t){this.message=t;},mutate(label,fn){this.mutations=(this.mutations||0)+1;fn();},timeline:{zoom:1,el:{querySelector:()=>({offsetWidth:244})},scroll:{clientWidth:800,scrollLeft:0},width(){return 556*this.zoom;},px(t){return t/a.doc.duration*this.width();},render(){this.renders=(this.renders||0)+1;}}};return a;}
test('view and key actions do not mutate the document or selection',()=>{const a=app(),before=JSON.stringify(a.doc);stepTimelineKey(a,1);assert.equal(a.time,2);assert.equal(frameTimelineRange(a),true);assert.equal(a.timeline.scroll.scrollLeft,0);assert.equal(JSON.stringify(a.doc),before);assert.deepEqual(a.selected,['a']);assert.equal(a.mutations,undefined);});
test('Next pose creates no keys, preserves Auto Key and only extension adds undo action',()=>{const a=app(),before=JSON.stringify(a.doc.layers);advanceNextPose(a);assert.equal(a.time,2);assert.equal(a.mutations,undefined);a.time=6;advanceNextPose(a);assert.equal(a.time,7);assert.equal(a.doc.duration,7);assert.equal(a.mutations,1);assert.equal(JSON.stringify(a.doc.layers),before);assert.equal(a.autoKey,false);assert.match(a.message,/Auto Key is off/);a.time=600;advanceNextPose(a);assert.equal(a.mutations,1);});
test('focused row scroll accounts for sticky ruler rather than placing label underneath it',()=>{const a=app(),row={dataset:{layer:'a'},classList:{contains:()=>false},getBoundingClientRect:()=>({top:90,bottom:134,height:44})};a.timeline.scroll.scrollTop=100;a.timeline.scroll.getBoundingClientRect=()=>({top:100,bottom:300});a.timeline.el.querySelectorAll=()=>[row];a.timeline.el.querySelector=s=>s==='.ruler'?{offsetHeight:44}:null;revealTimelineRow(a,'a');assert.equal(a.timeline.scroll.scrollTop,46);});
