import test from 'node:test';import assert from 'node:assert/strict';
import {Timeline} from '../dist/timeline/timeline.js';
import {bindTimelineRazor,cutSequenceBlock,copySequenceBlock,pasteSequenceBlock,setSequenceGesture,showSequenceClipboard} from '../dist/ui/timeline-razor.js';
import {object,project,History,clone} from '../dist/document/model.js';
import {putKey,evaluated} from '../dist/animation/evaluate.js';
import {layerBlocks,trimBlock} from '../dist/animation/blocks.js';
import {audioClips} from '../dist/audio/clips.js';
const pose=(n,time)=>{const v=evaluated(n,time);return {x:v.x,y:v.y,opacity:v.opacity,rotation:v.rotation,nodes:v.nodes};};
function fixture(){const n=object('rectangle'),a={doc:project(),selected:[],keyIds:new Set(),time:1.25,multi:false,ease:'linear',audio:{},properties:{flush(){}},stage:{finishPath(){}},pause(){},render(){},renderStage(){},toast(){},safe(fn){return fn();},seek(t){this.time=t;},dialogs:[]};a.doc.layers=[n];putKey(n,'x',0,0,'easeInOut');putKey(n,'x',5,100,'linear');putKey(n,'opacity',0,1,'linear');putKey(n,'opacity',5,.2,'linear');a.history=new History(()=>a.doc,p=>a.doc=p);a.mutate=(label,fn)=>a.history.run(label,fn);a.dialog=(title,body,opts)=>{const buttons=new Map(),d={title,body,opts,style:{},classList:{add(){}},querySelector(selector){if(!buttons.has(selector))buttons.set(selector,{});return buttons.get(selector);},close(){this.closed=true;}};a.dialogs.push(d);return d;};const t=Object.create(Timeline.prototype);Object.assign(t,{a,pointers:new Map(),touchMode:'razor',zoom:1,frameSnap:false,expandedBlocks:new Set(),collapsed:new Set(),scroll:{scrollLeft:0,scrollTop:0,setPointerCapture(){},hasPointerCapture(){return true;},releasePointerCapture(){},classList:{toggle(){}}},el:{querySelector:()=>({getBoundingClientRect:()=>({left:0}),style:{setProperty(){}}})},width:()=>600,time:e=>e.clientX/100,render(){},blockControls(){},editBlockTracks(){this.graphs=(this.graphs||0)+1;}});return {t,n,a};}
function event(t,x=250,{id=1,block=true,audio=false,type='touch',y=500,scope}={}){const node=t.a.doc.layers[0],b=audio?audioClips(t.a.doc.audio)[0]:(layerBlocks(node,t.a.doc).find(b=>x/100>=b.start&&x/100<b.end)||layerBlocks(node,t.a.doc)[0]),hit=block?{dataset:{block:b.id,...(audio?{}:{blockObject:node.id})}}:null,row={dataset:{layer:scope||node.id}},lane={closest:s=>s==='[data-layer]'&&!audio?row:s==='.audio-row'&&audio?{}:null};return {button:0,pointerId:id,pointerType:type,clientX:x,clientY:y,preventDefault(){},target:{closest:s=>s==='.track-lane'?lane:s==='[data-block]'?hit:null}};}
function clock(fn){const st=globalThis.setTimeout,ct=globalThis.clearTimeout,timers=new Map();let id=0;globalThis.setTimeout=(f,ms)=>{timers.set(++id,{f,ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);try{fn({fire(){for(const [id,t] of [...timers])if(t.ms===550){timers.delete(id);t.f();}},timers});}finally{globalThis.setTimeout=st;globalThis.clearTimeout=ct;}}
test('Razor tap cuts at the pointer frame with snapping off, preserves poses and leaves playhead unchanged; no double-tap graph',()=>clock(()=>{const {t,n,a}=fixture(),before=Array.from({length:121},(_,i)=>pose(n,i/24)),e=event(t,253);t.down(e);assert.equal(n.blocks,undefined);t.up(e);assert.equal(n.blocks.length,2);assert.equal(n.blocks[0].end,Math.round(2.53*24)/24);assert.equal(a.time,1.25);before.forEach((v,i)=>assert.deepEqual(pose(n,i/24),v));assert.equal(a.history.undoStack.length,1);t.down(event(t,350));t.up(event(t,350));assert.equal(n.blocks.length,3);assert.equal(t.graphs,undefined);assert.equal(a.time,1.25);a.history.undo();assert.equal(a.doc.layers[0].blocks.length,2);a.history.undo();assert.equal(a.doc.layers[0].blocks,undefined);}));
test('cutting a trimmed owned block preserves hold cuts, owned keys, unrelated tracks and frame-boundary poses',()=>{const {t,n,a}=fixture();n.blocks=[{id:'owned',name:'Owned',start:0,end:5,props:['x'],tracks:{x:clone(n.tracks.x)}}];trimBlock(n,a.doc,'owned',1,4);const cuts=clone(n.blockCuts),base=clone(n.tracks),samples=Array.from({length:121},(_,i)=>pose(n,i/24));assert.equal(cutSequenceBlock(t,{object:n.id,id:'owned'},2.513),true);assert.deepEqual(n.blockCuts,cuts);assert.deepEqual(n.tracks,base);assert.equal(n.blocks.length,2);assert.notEqual(n.blocks[0].tracks.x[0].id,n.blocks[1].tracks.x[0].id);samples.forEach((v,i)=>assert.deepEqual(pose(n,i/24),v));});
test('block endpoints, one-frame edge rounding and locked layers do not create empty blocks or undo entries',()=>{const {t,n,a}=fixture(),s={object:n.id,id:layerBlocks(n,a.doc)[0].id},before=clone(a.doc);for(const time of [0,.001,5,5.001,6,NaN])assert.equal(cutSequenceBlock(t,s,time),false);assert.deepEqual(a.doc,before);assert.equal(a.history.undoStack.length,0);n.locked=true;assert.equal(cutSequenceBlock(t,s,2),false);assert.equal(n.blocks,undefined);});
test('audio Razor preserves offsets and source trim continuity, then held-time paste creates one undo step without seek',()=>{const {t,a}=fixture();a.doc.audio={assetId:'asset',name:'Voice',offset:1,trimStart:2,trimEnd:7,duration:8,volume:1};const id=audioClips(a.doc.audio)[0].id;cutSequenceBlock(t,{object:'audio',id},3.5);const [left,right]=audioClips(a.doc.audio);assert.deepEqual([left.offset,left.trimStart,left.trimEnd],[1,2,4.5]);assert.deepEqual([right.offset,right.trimStart,right.trimEnd],[3.5,4.5,7]);copySequenceBlock(t,{object:'audio',id:right.id});pasteSequenceBlock(t,5);assert.equal(a.time,1.25);assert.equal(audioClips(a.doc.audio).at(-1).offset,5);assert.equal(audioClips(a.doc.audio).at(-1).trimStart,4.5);assert.equal(a.doc.duration,7.5);assert.equal(a.history.undoStack.length,2);a.history.undo();assert.equal(audioClips(a.doc.audio).length,2);a.history.undo();assert.equal(a.doc.audio.clips,undefined);});
test('stationary block hold in Razor opens modeless clipboard without cutting; release does nothing and paste uses held frame',()=>clock(c=>{const {t,n,a}=fixture(),e=event(t,250);copySequenceBlock(t,{object:n.id,id:layerBlocks(n,a.doc)[0].id});t.down(e);c.fire();assert.equal(t.g,null);assert.equal(t.pointers.size,0);assert.equal(a.dialogs.length,1);const d=a.dialogs[0];assert.deepEqual(d.opts,{modal:false});assert.match(d.body,/Copy block/);assert.match(d.body,/Frame 60/);t.up(e);assert.equal(n.blocks,undefined);assert.equal(a.history.undoStack.length,0);d.querySelector('[data-sequence-paste]').onclick();assert.equal(n.blocks.at(-1).start,2.5);assert.equal(a.time,1.25);assert.equal(a.history.undoStack.length,1);assert.equal(d.closed,true);}));
test('movement, second pointer and pointercancel cancel the held menu and pending Razor cut',()=>clock(c=>{for(const action of ['move','second','cancel']){const {t,n,a}=fixture(),e=event(t,250);t.down(e);if(action==='move')t.move({...e,clientX:270});if(action==='second')t.down(event(t,350,{id:2}));if(action==='cancel')t.cancel(e);c.fire();assert.equal(a.dialogs.length,0);if(action==='second'){t.up(event(t,350,{id:2}));t.up(e);}else t.up({...e,clientX:270});assert.equal(n.blocks,undefined);assert.equal(a.history.undoStack.length,0);assert.equal(c.timers.size,0);}}));
test('blank lane hold offers matching clipboard only; animation paste labels and retains its source-layer owner',()=>clock(c=>{const {t,n,a}=fixture();t.touchMode='select';copySequenceBlock(t,{object:n.id,id:layerBlocks(n,a.doc)[0].id});t.down(event(t,350,{block:false}));c.fire();assert.match(a.dialogs[0].body,/Paste into Rectangle here/);assert.match(a.dialogs[0].body,/data-sequence-copy disabled/);t.up(event(t,350,{block:false}));assert.equal(a.history.undoStack.length,0);const d=showSequenceClipboard(t,{clientX:300,clientY:500},null,'audio',3);assert.match(d.body,/data-sequence-paste disabled/);d.querySelector('[data-sequence-copy]').onclick();assert.equal(a.history.undoStack.length,0);}));
test('normal block movement still moves in one undo step and suppresses the clipboard hold',()=>clock(c=>{const {t,n,a}=fixture();t.touchMode='select';const e=event(t,150);t.down(e);t.move({...e,clientX:250});c.fire();t.up({...e,clientX:250});assert.equal(a.dialogs.length,0);assert.equal(a.history.undoStack.length,1);assert.equal(a.doc.layers[0].blocks[0].start,1);a.history.undo();assert.equal(a.doc.layers[0].blocks,undefined);}));
test('Razor button and gesture selector share real mode state; visibility cancellation clears a pending hold without cutting',()=>clock(c=>{
 const old=globalThis.document,{t,n,a}=fixture(),elements=new Map(),listeners=new Map(),options=[];let button;
 const selector={value:'select',querySelector:()=>options.find(o=>o.value==='razor'),append(o){options.push(o);}},toolbar={querySelector:()=>({after(b){button=b;elements.set('#timeline-razor',b);}})};
 elements.set('#timeline-touch-mode',selector);elements.set('.block-toolbar',toolbar);globalThis.document={hidden:false,querySelector:s=>elements.get(s),createElement:tag=>({tagName:tag.toUpperCase(),attrs:{},setAttribute(k,v){this.attrs[k]=v;},classList:{toggle(){}}}),addEventListener:(event,fn)=>listeners.set(event,fn)};
 try{t.touchMode='select';bindTimelineRazor(t);assert.equal(options[0].value,'razor');assert.match(button.innerHTML,/<svg/);button.onclick();assert.equal(t.touchMode,'razor');assert.equal(selector.value,'razor');assert.equal(button.attrs['aria-pressed'],true);selector.onchange({target:{value:'select'}});assert.equal(t.touchMode,'select');assert.equal(button.attrs['aria-pressed'],false);
  button.onclick();t.down(event(t,250));assert.equal(c.timers.size,1);globalThis.document.hidden=true;listeners.get('visibilitychange')();c.fire();assert.equal(t.pointers.size,0);assert.equal(t.g,null);assert.equal(n.blocks,undefined);assert.equal(a.dialogs.length,0);assert.equal(a.history.undoStack.length,0);
 }finally{globalThis.document=old;}
}));
test('Razor drag release alone cancels a cut even if no move event was delivered; canceled audio clipboard actions remain inert',()=>clock(()=>{
 const {t,n,a}=fixture(),e=event(t,250);t.down(e);t.up({...e,clientX:270});assert.equal(n.blocks,undefined);copySequenceBlock(t,{object:n.id,id:layerBlocks(n,a.doc)[0].id});const d=showSequenceClipboard(t,{clientX:10,clientY:500},null,'audio',3);d.querySelector('[data-sequence-paste]').onclick();assert.equal(n.blocks,undefined);assert.equal(a.history.undoStack.length,0);
}));
