import test from 'node:test';import assert from 'node:assert/strict';
import {Timeline,timelineTrackScopes,timelineKeySummary,timelineRecordingStatus,timelineTrackAddAttributes} from '../dist/timeline/timeline.js';
import {project,object} from '../dist/document/model.js';import {putKey} from '../dist/animation/evaluate.js';
function fixture(){const n=object('rectangle'),p=project();p.layers=[n];putKey(n,'x',0,0);putKey(n,'x',2,100);return {n,p};}
function harness(n,p){const t=Object.create(Timeline.prototype);t.a={doc:p,time:1,selected:[n.id],keyIds:new Set()};t.collapsed=new Set();t.expandedBlocks=new Set();t.expandedLayers=new Set();t.blockSelection=null;t.zoom=1;t.measurement='seconds';t.el={style:{setProperty(){}},innerHTML:''};t.scroll={clientWidth:1000,scrollLeft:17,scrollTop:23};t.playhead=()=>{};t.waveform=()=>{};t.blockControls=()=>{};return t;}
function render(t){const previous=globalThis.document,controls=new Map();globalThis.document={querySelector(selector){if(!controls.has(selector))controls.set(selector,{});return controls.get(selector);}};try{t.render();return t.el.innerHTML;}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous;}}
test('selecting animated artwork immediately shows its parameter keys, count and real disclosure state',()=>{const {n,p}=fixture(),t=harness(n,p);let html=render(t);assert.match(html,/data-track-scope="base"/);assert.match(html,/Position X/);assert.match(html,/2 keys/);assert.match(html,/aria-expanded="true"/);for(const k of n.tracks.x)assert.match(html,new RegExp(`data-keyid="${k.id}"`));assert.equal(t.scroll.scrollLeft,17);assert.equal(t.scroll.scrollTop,23);t.a.selected=[];html=render(t);assert.doesNotMatch(html,/property-row/);assert.match(html,/aria-expanded="false"/);});
test('chevron opens an unselected layer and explicitly collapsed selected layers stay collapsed',()=>{const {n,p}=fixture(),t=harness(n,p);t.a.selected=[];t.render=()=>{};assert.equal(t.layerOpen(n),false);t.toggleLayer(n.id);assert.equal(t.layerOpen(n),true);t.a.selected=[n.id];t.toggleLayer(n.id);assert.equal(t.layerOpen(n),false);t.toggleLayer(n.id);assert.equal(t.layerOpen(n),true);});
test('selected and active block scopes are prioritised without hiding base edits or endpoint keys',()=>{const {n,p}=fixture();putKey(n,'x',5,300);n.blocks=[{id:'first',name:'First move',start:0,end:2,props:['y'],tracks:{y:[{id:'start',time:0,value:0,easing:'linear'},{id:'end',time:2,value:40,easing:'linear'},{id:'outside',time:4,value:60,easing:'linear'}]}},{id:'second',name:'Second move',start:3,end:5,props:['opacity'],tracks:{opacity:[{id:'fade',time:4,value:.5,easing:'linear'}]}}];const scopes=timelineTrackScopes(n,p,{object:n.id,id:'first'},4);assert.deepEqual(scopes.map(s=>s.id),['first','second','base']);assert.deepEqual(scopes[0].tracks[0][1].map(k=>k.id),['start','end']);assert.equal(scopes[2].tracks[0][1].at(-1).time,5);assert.equal(timelineTrackScopes(n,p,null,4)[0].id,'second');assert.equal(timelineTrackScopes(n,p,{object:'other',id:'first'},4)[0].id,'second');const t=harness(n,p);t.blockSelection={object:n.id,id:'first'};t.a.time=4;const html=render(t);assert.match(html,/First move · 2 keys/);assert.match(html,/Base animation · 3 keys/);assert.match(html,/Second move · 1 key/);assert.match(html,/data-keyid="end"/);assert.match(html,/6 keys/);});
test('synthetic base blocks do not duplicate keys and group children remain disclosed',()=>{const {n,p}=fixture(),g=object('group',{children:[n]}),t=harness(n,p);assert.equal(timelineTrackScopes(n,p,null,1).length,1);assert.equal(t.layerOpen(g),true);t.collapsed.add(g.id);assert.equal(t.layerOpen(g),false);});

test('unselected inactive block tracks require explicit expansion while totals still report all keys',()=>{const {n,p}=fixture();n.blocks=Array.from({length:100},(_,i)=>({id:'b'+i,name:'Move '+i,start:3,end:4,props:['y'],tracks:{y:[{id:'k'+i,time:3,value:i,easing:'linear'}]}}));assert.deepEqual(timelineTrackScopes(n,p,null,1).map(s=>s.id),['base']);assert.deepEqual(timelineTrackScopes(n,p,null,1,new Set(['b7'])).map(s=>s.id),['base','b7']);assert.equal(timelineKeySummary(n,p,1).total,102);});
test('recording feedback reports Auto Key mode, frame, counts and same-frame overwrite guidance',()=>{const {n,p}=fixture(),a={doc:p,selected:[n.id],time:2,autoKey:true};assert.match(timelineRecordingStatus(a),/Auto Key on · Frame 48/);assert.match(timelineRecordingStatus(a),/2 keys · 1 here · Advance playhead for a new key/);a.time=1;assert.doesNotMatch(timelineRecordingStatus(a),/Advance playhead/);a.autoKey=false;assert.match(timelineRecordingStatus(a),/Auto Key off/);a.selected=[];assert.match(timelineRecordingStatus(a),/Select artwork/);});
function withDOM(fn){const previous=globalThis.document,controls=new Map();globalThis.document={querySelector(selector){if(!controls.has(selector))controls.set(selector,{});return controls.get(selector);}};try{return fn(controls);}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous;}}
test('render integrates recording feedback and preserves selected-key details with a full tooltip',()=>{const {n,p}=fixture(),t=harness(n,p);withDOM(controls=>{t.a.autoKey=true;t.a.time=2;t.render();let status=controls.get('#key-status');assert.match(status.textContent,/Auto Key on · Frame 48 · 2 keys · 1 here/);assert.equal(status.title,status.textContent);t.a.keyIds.add(n.tracks.x[0].id);t.render();assert.equal(status.textContent,'Position X · 0.00s');assert.equal(status.title,status.textContent);});});
test('paused stage edits immediately expose new keys; seeking only refreshes feedback until scope changes',()=>{const {n,p}=fixture(),t=harness(n,p);withDOM(controls=>{let renders=0;const original=t.render.bind(t);t.render=()=>{renders++;original();};t.render();assert.equal(renders,1);t.a.time=2;t.refreshRecording();assert.equal(renders,1);assert.match(controls.get('#key-status').textContent,/Frame 48 · 2 keys · 1 here/);putKey(n,'y',2,100);t.refreshRecording();assert.equal(renders,2);assert.match(t.el.innerHTML,/Position Y/);assert.match(controls.get('#key-status').textContent,/3 keys · 2 here/);putKey(n,'y',2,200);t.refreshRecording();assert.equal(renders,2);assert.equal(t.scroll.scrollTop,23);n.blocks=[{id:'b',name:'Block',start:3,end:5,props:['opacity'],tracks:{opacity:[{id:'o',time:4,value:.5,easing:'linear'}]}}];t.refreshRecording();const before=renders;assert.doesNotMatch(t.el.innerHTML,/data-track-scope="b"/);t.a.time=4;t.refreshRecording();assert.equal(renders,before+1);assert.match(t.el.innerHTML,/data-track-scope="b"/);});});
test('live recording refresh defers during playback, timeline gestures and graph gestures',()=>{const {n,p}=fixture(),t=harness(n,p);let renders=0,statuses=0;t.render=()=>renders++;t.updateRecordingStatus=()=>statuses++;t.a.playing=true;t.refreshRecording();t.a.playing=false;t.g={type:'keys'};t.refreshRecording();t.g=null;t.a.graphGestureActive=true;t.refreshRecording();assert.equal(renders,0);assert.equal(statuses,0);t.a.graphGestureActive=false;t.refreshRecording();assert.equal(renders,1);});
function ownedFixture(){const {n,p}=fixture();n.blocks=[{id:'owned',name:'Owned move',start:0,end:2,props:['x'],tracks:{x:[{id:'owned0',time:0,value:500,easing:'linear'},{id:'owned2',time:2,value:700,easing:'linear'}]}}];return {n,p};}
function clickAdd(t,scope,prop='x'){const track={dataset:{object:t.a.doc.layers[0].id,trackKey:prop,keyScope:scope}};t.click({target:{closest(selector){return selector==='[data-track-key]'?track:null;}}});}
test('row Add routes Base and owned block keys independently using each source interpolation',()=>{const {n,p}=ownedFixture(),t=harness(n,p);let mutations=0;t.a.mutate=(label,fn)=>{mutations++;fn();};t.a.ease='linear';clickAdd(t,'base');assert.equal(n.tracks.x.find(k=>k.time===1).value,50);assert.equal(n.blocks[0].tracks.x.length,2);clickAdd(t,'owned');assert.equal(n.blocks[0].tracks.x.find(k=>k.time===1).value,600);assert.equal(n.tracks.x.length,3);assert.equal(mutations,2);assert.equal(t.a.keyIds.size,1);const html=render(t);assert.match(html,/data-track-key="x"[^>]*data-key-scope="base"/);assert.match(html,/data-track-key="x"[^>]*data-key-scope="owned"/);});
test('owned row Add accepts its endpoint but refuses inactive out-of-range routing with explanatory disabled title',()=>{const {n,p}=ownedFixture(),t=harness(n,p);let mutations=0;t.a.mutate=(label,fn)=>{mutations++;fn();};t.a.time=3;t.expandedBlocks.add('owned');clickAdd(t,'owned');assert.equal(mutations,0);assert.equal(n.blocks[0].tracks.x.length,2);assert.match(timelineTrackAddAttributes(n,p,'x',{id:'owned',name:'Owned move'},3),/disabled title="Place playhead in Owned move/);t.a.time=2;clickAdd(t,'owned');assert.equal(mutations,1);assert.equal(n.blocks[0].tracks.x.length,2);assert.equal(n.blocks[0].tracks.x.at(-1).value,700);t.a.time=3;clickAdd(t,'base');assert.equal(mutations,2);assert.equal(n.tracks.x.at(-1).time,3);assert.equal(n.tracks.x.at(-1).value,100);});
test('active scope ownership is per property and suppresses only fully shadowed sources',()=>{const {n,p}=fixture();n.blocks=[{id:'x',name:'X motion',start:0,end:2,props:['x'],tracks:{x:[{id:'xkey',time:1,value:10,easing:'linear'}]}},{id:'y',name:'Y motion',start:0,end:2,props:['y'],tracks:{y:[{id:'ykey',time:1,value:20,easing:'linear'}]}},{id:'newx',name:'Later X',start:0,end:2,props:['x'],tracks:{x:[{id:'newxkey',time:1,value:30,easing:'linear'}]}}];assert.deepEqual(timelineTrackScopes(n,p,null,1).map(s=>s.id),['y','newx','base']);assert.equal(timelineTrackScopes(n,p,{object:n.id,id:'x'},1)[0].id,'x');assert.ok(timelineTrackScopes(n,p,null,1,new Set(['x'])).some(s=>s.id==='x'));n.blocks[0].tracks.rotation=[{id:'r',time:1,value:5,easing:'linear'}];const scopes=timelineTrackScopes(n,p,null,1);assert.deepEqual(scopes.find(s=>s.id==='x').tracks.map(([prop])=>prop),['rotation']);});
test('tapping an automatically shown endpoint pins its owning scope before seek without overriding collapse',()=>{const {n,p}=ownedFixture(),t=harness(n,p);t.a.audio={};t.a.pause=()=>{};t.a.properties={flush(){}};t.a.stage={finishPath(){}};t.a.history={begin(){}};t.a.seek=time=>{t.a.time=time;t.refreshRecording();};t.pointers=new Map();t.scroll.setPointerCapture=()=>{};const hit={dataset:{keyid:'owned2',object:n.id,keyScope:'owned'}},lane={};withDOM(()=>{t.render();t.down({button:0,pointerId:1,clientX:500,clientY:100,preventDefault(){},target:{closest(selector){return selector==='.track-lane'?lane:selector==='[data-keyid]'?hit:null;}}});assert.equal(t.a.time,2);assert.ok(t.expandedBlocks.has('owned'));assert.ok(t.a.keyIds.has('owned2'));assert.match(t.el.innerHTML,/data-keyid="owned2"/);t.collapsed.add(n.id);t.render();assert.doesNotMatch(t.el.innerHTML,/data-keyid="owned2"/);});});
