import test from 'node:test';import assert from 'node:assert/strict';
import {layerBlocks,isolateBlock,trimBlock,splitBlock,moveBlock} from '../dist/animation/blocks.js';
import {configureAutoKey,setProperty,putKey,evaluated} from '../dist/animation/evaluate.js';
import {Timeline} from '../dist/timeline/timeline.js';import {MotionRecorder} from '../dist/animation/record-motion.js';import {refreshRecordMotion} from '../dist/ui/record-motion.js';
import {project,object,clone,History} from '../dist/document/model.js';import {validate} from '../dist/document/validate.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} differs from ${b}`);
function fixture(){const p=project(),n=object('rectangle');p.layers=[n];putKey(n,'x',0,0,'linear');putKey(n,'x',2,100,'linear');return {p,n};}
test('concrete later Auto Key pose is visible after graph isolation without stretching the original owned block',()=>{
 const {p,n}=fixture(),owned=isolateBlock(n,p,layerBlocks(n,p)[0].id),before=clone(owned);configureAutoKey(p,true,'linear');setProperty(n,'x',200,4);assert.equal(n.tracks.x.at(-1).time,4);assert.equal(evaluated(n,3).x,150);const ranges=layerBlocks(n,p);assert.deepEqual(n.blocks,[before]);assert.equal(ranges.length,2);assert.deepEqual([ranges[1].start,ranges[1].end],[2,4]);assert.equal(ranges[1].generated,true);assert.deepEqual(ranges[1].props,['x']);assert.equal(n.blocks.length,1);validate(clone(p));
});
test('generated base extents include rotation, noise, shadow and mesh keys and recompute without document mutation',()=>{
 const {p,n}=fixture();isolateBlock(n,p,layerBlocks(n,p)[0].id);putKey(n,'rotation',0,0);putKey(n,'rotation',5,720);putKey(n,'lineNoiseAmplitude',0,6);putKey(n,'lineNoiseAmplitude',4,12);putKey(n,'shadowBlur',0,12);putKey(n,'shadowBlur',3,10);const mesh={rows:2,cols:2,bounds:{x:0,y:0,width:10,height:10},points:[{x:0,y:0,color:'#000000'},{x:10,y:0,color:'#000000'},{x:0,y:10,color:'#000000'},{x:10,y:10,color:'#000000'}]};putKey(n,'mesh',0,mesh);putKey(n,'mesh',4,mesh);const before=clone(p),range=layerBlocks(n,p).find(b=>b.generated);assert.equal(range.end,5);assert.deepEqual(new Set(range.props),new Set(['rotation','lineNoiseAmplitude','shadowBlur','mesh']));assert.deepEqual(p,before);putKey(n,'rotation',5.5,900);assert.equal(layerBlocks(n,p).find(b=>b.generated).end,5.5);
});
test('split, trimmed and moved block ranges remain explicit; held or owned source keys do not reappear as extra blocks',()=>{
 const {p,n}=fixture(),id=layerBlocks(n,p)[0].id;splitBlock(n,p,id,1);assert.equal(layerBlocks(n,p).length,2);trimBlock(n,p,n.blocks[1].id,1,1.5);const explicit=clone(n.blocks),cuts=clone(n.blockCuts);assert.equal(layerBlocks(n,p).length,2);putKey(n,'x',4,200);const generated=layerBlocks(n,p).find(b=>b.generated);assert.deepEqual([generated.start,generated.end],[2,4]);assert.deepEqual(n.blocks,explicit);assert.deepEqual(n.blockCuts,cuts);moveBlock(n,p,n.blocks[0].id,4.5);assert.equal(n.blocks[0].end,5.5);putKey(n,'rotation',5.75,360);assert.equal(n.blocks[0].end,5.5);validate(clone(p));
});
test('editing a computed base range materializes that range once, then its split boundaries remain fixed',()=>{
 const {p,n}=fixture();isolateBlock(n,p,layerBlocks(n,p)[0].id);putKey(n,'x',4,200);const generated=layerBlocks(n,p).find(b=>b.generated);splitBlock(n,p,generated.id,3);assert.deepEqual(n.blocks.map(b=>[b.start,b.end]),[[0,2],[2,3],[3,4]]);assert.ok(n.blocks.every(b=>!b.generated));putKey(n,'x',5,250);assert.deepEqual(n.blocks.map(b=>[b.start,b.end]),[[0,2],[2,3],[3,4]]);assert.deepEqual(layerBlocks(n,p).filter(b=>b.generated).map(b=>[b.start,b.end]),[[4,5]]);
});
function dom(fn){const old=globalThis.document,controls=new Map();globalThis.document={activeElement:null,querySelector(id){if(!controls.has(id))controls.set(id,{classList:{toggle(){}},setAttribute(){},style:{setProperty(){}}});return controls.get(id);}};try{return fn(controls);}finally{globalThis.document=old;}}
function timeline(n,p){const t=Object.create(Timeline.prototype);t.a={doc:p,time:1,selected:[n.id],keyIds:new Set(),autoKey:true};Object.assign(t,{collapsed:new Set(),expandedBlocks:new Set(),expandedLayers:new Set(),blockSelection:null,zoom:1,measurement:'seconds',scroll:{clientWidth:1000,scrollLeft:17,scrollTop:23},el:{style:{setProperty(){}},innerHTML:''},playhead(){},waveform(){}});return t;}
test('refreshRecording invalidates stale sequence widths when an existing endpoint key changes time without adding keys',()=>dom(()=>{
 const {p,n}=fixture(),t=timeline(n,p);t.render();assert.match(t.el.innerHTML,/width:33.33333333333333%/);n.tracks.x.at(-1).time=4;t.refreshRecording();assert.match(t.el.innerHTML,/width:66.66666666666666%/);assert.equal(t.scroll.scrollTop,23);
}));
test('actual Record motion refresh updates base-range DOM during the take and full sequence extent on release',()=>dom(controls=>{
 const {p,n}=fixture();isolateBlock(n,p,layerBlocks(n,p)[0].id);const t=timeline(n,p),a=t.a;a.time=3;a.tool='select';a.recordMotionArmed=true;a.pause=()=>{};a.toast=()=>{};a.renderStage=()=>refreshRecordMotion(a);a.history=new History(()=>a.doc,next=>a.doc=next);let now=0;const recorder=new MotionRecorder(a,{now:()=>now,raf:()=>1,cancelRaf(){}});a.motionRecorder=recorder;a.timeline=t;const elements=[];const lane={insertAdjacentHTML(where,html){const id=html.match(/data-block="([^"]+)"/)[1],element={dataset:{block:id},parentElement:lane,values:{},style:{setProperty(k,v){element.values[k]=v;}},setAttribute(k,v){element[k]=v;},remove(){elements.splice(elements.indexOf(element),1);}};elements.push(element);},querySelector(selector){return elements.find(e=>selector.includes(e.dataset.block));}};t.el.querySelectorAll=()=>elements;t.el.querySelector=()=>lane;
 a.history.begin();const gesture={type:'move',started:true,edit:true,items:[{id:n.id,v:clone(evaluated(n,3))}]};recorder.begin(gesture);recorder.pose([{id:n.id,x:200,y:30}]);now=500;recorder.tick();let range=layerBlocks(n,p).find(b=>b.generated),element=elements.find(e=>e.dataset.block===range.id);near(range.end,3.5);near(Number.parseFloat(element.values.width),(3.5-2)/6*100);t.blockSelection={object:n.id,id:range.id};now=1000;recorder.tick();range=layerBlocks(n,p).find(b=>b.generated);near(range.end,4);near(Number.parseFloat(element.values.width),100/3);assert.match(controls.get('#block-status').textContent,/4s/);assert.match(controls.get('#key-status').textContent,/Frame 96/);assert.equal(n.blocks[0].end,2);recorder.finish();a.history.commit('Take');t.render();assert.match(t.el.innerHTML,/Base automation/);assert.equal(a.history.undoStack.length,1);assert.equal(t.scroll.scrollTop,23);a.history.undo();assert.equal(layerBlocks(a.doc.layers[0],a.doc).length,1);
}));
test('actual Edit key FormData handler clamps noise and shadow values while preserving opacity rejection and undo',()=>dom(()=>{
 for(const [prop,initial,input,expected] of [['lineNoiseAmplitude',6,-20,0],['lineNoiseSize',40,0,2],['lineNoiseSpeed',1,500,60],['lineNoiseSeed',1,-2e6,-1e6],['shadowBlur',12,400,200],['shadowOpacity',.35,5,1]]){const {p,n}=fixture(),key=putKey(n,prop,1,initial),t=timeline(n,p),a=t.a;a.keyIds=new Set([key.id]);a.history=new History(()=>a.doc,next=>a.doc=next);a.mutate=(label,fn)=>a.history.run(label,fn);a.seek=time=>a.time=time;let apply;a.dialog=(title,body,action)=>{apply=action;return {close(){}};};t.editSelected();const form=new FormData();form.set('time','1');form.set('value',String(input));form.set('ease','linear');apply(form,{close(){}});assert.equal(key.value,expected);validate(clone(a.doc));assert.equal(a.history.undoStack.length,1);a.history.undo();assert.equal(a.doc.layers[0].tracks[prop][0].value,initial);}
 const {p,n}=fixture(),key=putKey(n,'opacity',1,.5),t=timeline(n,p);t.a.keyIds=new Set([key.id]);let apply;t.a.dialog=(title,body,action)=>{apply=action;return {};};const form=new FormData();form.set('time','1');form.set('value','5');form.set('ease','linear');t.editSelected();assert.throws(()=>apply(form,{}),/outside this track/);assert.equal(key.value,.5);
}));
test('recording composition extension refreshes all layer/audio percentages and ruler once the duration changes',()=>dom(()=>{
 const {p,n}=fixture(),other=object('rectangle');p.duration=3;p.layers.push(other);putKey(other,'opacity',0,1);putKey(other,'opacity',2,.5);p.audio={assetId:'audio',name:'Voice',offset:1,trimStart:0,trimEnd:1,duration:1,volume:1};const t=timeline(n,p);t.render();assert.match(t.el.innerHTML,/left:33.33333333333333%;width:33.33333333333333%/);t.a.motionRecorder={active:true};t.el.querySelectorAll=()=>[];p.duration=4;putKey(n,'x',3.5,200);t.refreshMotionRanges();assert.equal(t.renderedDuration,4);assert.match(t.el.innerHTML,/left:25%;width:25%/);assert.match(t.el.innerHTML,/width:87.5%/);assert.equal(t.scroll.scrollTop,23);
}));
test('computed ranges for unrelated new parameters cannot collide with a materialized generated block ID',()=>{
 const {p,n}=fixture();isolateBlock(n,p,layerBlocks(n,p)[0].id);putKey(n,'rotation',0,0);putKey(n,'rotation',4,360);const first=layerBlocks(n,p).find(b=>b.generated);isolateBlock(n,p,first.id);putKey(n,'shadowBlur',0,12);putKey(n,'shadowBlur',4,20);const ranges=layerBlocks(n,p);assert.equal(new Set(ranges.map(b=>b.id)).size,ranges.length);assert.equal(ranges.find(b=>b.generated).end,4);validate(clone(p));
});
