import test from 'node:test';import assert from 'node:assert/strict';
import {readWorkspacePreferences,initWorkspace,setGuidedWorkspace,setInspector,syncControlCopies,bindControlCopies} from '../dist/ui/workspace.js';
import {contextControls,renderContext} from '../dist/ui/context.js';
import {showShapes,chooseShape} from '../dist/ui/shapes-menu.js';
import {project,object,clone} from '../dist/document/model.js';
import {createMesh} from '../dist/scene/mesh.js';

function harness(){const previous={document:globalThis.document,localStorage:globalThis.localStorage},stored=new Map(),classes=new Set(),buttons=[{setAttribute(name,value){this[name]=value;}}],context={innerHTML:'',contains(){return false;}},inspector={classList:{toggle(name,on){if(on)classes.add(name);else classes.delete(name);}}};globalThis.localStorage={getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)};globalThis.document={documentElement:{dataset:{}},activeElement:null,querySelector:s=>s==='.inspector'?inspector:s==='#context-bar'?context:null,querySelectorAll:()=>buttons,getElementById:()=>null};return {stored,context,classes,buttons,restore(){globalThis.document=previous.document;globalThis.localStorage=previous.localStorage;}};}
test('workspace preferences default to guided navigation and tolerate corrupt storage',()=>{
 assert.deepEqual(readWorkspacePreferences({getItem:()=>null}),{guided:true,inspectorOpen:false});
 assert.deepEqual(readWorkspacePreferences({getItem:()=>'{broken'}),{guided:true,inspectorOpen:false});
 assert.deepEqual(readWorkspacePreferences({getItem:()=>'{"guided":false,"inspectorOpen":true}'}),{guided:false,inspectorOpen:true});
 assert.deepEqual(readWorkspacePreferences({getItem:()=>'{"guided":"false","inspectorOpen":1}'}),{guided:true,inspectorOpen:false});
});
test('Scaffold changes workspace navigation without changing artwork, tools or editing handles',()=>{const h=harness();try{const doc=project(),n=object('rectangle');doc.layers=[n];let layouts=0;const a={doc,selected:[n.id],tool:'direct',nodeEdit:true,showScaffold:false,stage:{layout(){layouts++;}},render(){},properties:{flush(){}}},before=clone(doc);initWorkspace(a);assert.equal(a.workspaceGuided,true);assert.equal(a.showScaffold,true);setGuidedWorkspace(a,false);assert.equal(a.workspaceGuided,false);assert.equal(a.showScaffold,true);assert.equal(a.tool,'direct');assert.equal(a.nodeEdit,true);assert.deepEqual(a.doc,before);assert.deepEqual(a.selected,[n.id]);assert.equal(globalThis.document.documentElement.dataset.workspace,'detailed');assert.ok(layouts>=2);const saved=JSON.parse(h.stored.get('poppy-workspace-v2'));assert.equal(saved.guided,false);}finally{h.restore();}});
test('Properties collapse is persistent and resizes the stage in both workspace modes',()=>{const h=harness();try{let layouts=0,flushes=0;const a={properties:{flush(){flushes++;}},stage:{layout(){layouts++;}},render(){}};initWorkspace(a);assert.equal(h.classes.has('open'),false);setInspector(a,true);assert.equal(h.classes.has('open'),true);assert.equal(h.buttons[0]['aria-expanded'],true);setGuidedWorkspace(a,false);setInspector(a,false);assert.equal(h.classes.has('open'),false);assert.equal(JSON.parse(h.stored.get('poppy-workspace-v2')).inspectorOpen,false);assert.equal(flushes,2);assert.ok(layouts>=4);}finally{h.restore();}});
test('guided context removes the empty control band but preserves full contextual actions',()=>{const h=harness();try{const doc=project(),n=object('rectangle');doc.layers=[n];const a={doc,selected:[n.id],tool:'select',workspaceGuided:true,workspaceInitialized:true,propertiesOpen:false,showScaffold:true,time:0,drawColor:'#888888'};renderContext(a);assert.match(h.context.innerHTML,/guided-context/);assert.match(h.context.innerHTML,/Object options/);assert.doesNotMatch(h.context.innerHTML,/context-actions|data-scaffold|data-edit="mesh"/);assert.match(contextControls(a).body,/data-edit="mesh"/);assert.match(contextControls(a).body,/data-edit="texture"/);a.workspaceGuided=false;renderContext(a);assert.match(h.context.innerHTML,/detailed-context/);assert.match(h.context.innerHTML,/data-edit="mesh"/);a.selected=[];renderContext(a);assert.doesNotMatch(h.context.innerHTML,/Choose Shapes →/);}finally{h.restore();}});
test('mesh placement prompts and edit actions are shared by guided and detailed contexts',()=>{const n=object('rectangle',{mesh:createMesh({x:0,y:0,width:100,height:100})}),doc=project();doc.layers=[n];const a={doc,selected:[n.id],tool:'mesh',time:0,activeMesh:0,meshPlacement:{id:n.id,first:null}};let result=contextControls(a);assert.match(result.mode,/Tap first side/);assert.match(result.body,/data-edit="mesh-bounds"/);assert.match(result.body,/data-edit="mesh-insert"/);assert.match(result.body,/data-edit="mesh-placement-cancel"/);a.meshPlacement.first={x:0,y:0};assert.match(contextControls(a).mode,/Tap opposite side/);delete a.meshPlacement;a.meshInsert=true;assert.match(contextControls(a).mode,/Tap inside shading/);});
test('Shapes uses a single labelled popup in guided mode and inline choices in detailed mode',()=>{const h=harness();try{let title,markup,closed=false,renderCount=0;const buttons=[{dataset:{shape:'star'}}],d={classList:{add(){}},querySelectorAll:()=>buttons,addEventListener(){},close(){closed=true;}};const a={workspaceInitialized:true,workspaceGuided:true,tool:'select',render(){renderCount++;},stage:{finishPath(){}},dialog(t,html){title=t;markup=html;return d;}};showShapes(a);assert.equal(title,'Shapes');assert.match(markup,/data-shape="triangle"/);assert.equal(a.tool,'select');buttons[0].onclick();assert.equal(a.tool,'star');assert.equal(a.shapesOpen,false);assert.equal(closed,true);a.workspaceGuided=false;a.shapesOpen=false;showShapes(a);assert.equal(a.shapesOpen,true);chooseShape(a,'ellipse');assert.equal(a.shapesOpen,true);assert.equal(a.tool,'ellipse');assert.ok(renderCount>=4);}finally{h.restore();}});
test('popup selectors forward changes and refresh newly enabled actions and toggle labels',async()=>{const previous=globalThis.document;try{
 const make=(tag,id)=>({tagName:tag,dataset:{workspaceControl:id},disabled:false,className:'',innerHTML:'',value:'',attrs:new Map(),getAttribute(name){return this.attrs.get(name)??null;},hasAttribute(name){return this.attrs.has(name);},setAttribute(name,value){this.attrs.set(name,value);},removeAttribute(name){this.attrs.delete(name);},matches(){return false;},closest(selector){return selector.startsWith('button')?(this.tagName==='BUTTON'?this:null):this.tagName==='SELECT'?this:null;}});
 const sourceSelect=make('SELECT','block-selector'),sourceButton=make('BUTTON','edit-block-tracks'),sourceToggle=make('BUTTON','snap-frames');sourceSelect.innerHTML='<option>Choose block</option>';sourceButton.disabled=true;sourceButton.innerHTML='Edit tracks';sourceToggle.setAttribute('aria-pressed','false');sourceToggle.innerHTML='Snap off';
 const sources={'block-selector':sourceSelect,'edit-block-tracks':sourceButton,'snap-frames':sourceToggle},copies=Object.entries(sources).map(([id,s])=>make(s.tagName,id)),listeners={},dialog={close(){throw Error('Selectors and toggles must not close the popup');}},el={querySelectorAll(){return copies;},addEventListener(name,fn){listeners[name]=fn;},closest(){return dialog;}};
 globalThis.document={getElementById:id=>sources[id],activeElement:null};sourceSelect.dispatchEvent=e=>{if(e.type==='change'){sourceButton.disabled=false;sourceToggle.setAttribute('aria-pressed','true');sourceToggle.className='active';sourceToggle.innerHTML='Snap on';sourceSelect.innerHTML='<option value="one">Block one</option>';}};
 bindControlCopies({},el);assert.equal(copies[1].disabled,true);copies[0].value='one';listeners.change({target:copies[0]});assert.equal(sourceSelect.value,'one');assert.equal(copies[1].disabled,false);assert.equal(copies[2].getAttribute('aria-pressed'),'true');assert.equal(copies[2].innerHTML,'Snap on');assert.equal(copies[0].innerHTML,sourceSelect.innerHTML);
 sourceToggle.click=()=>{sourceToggle.setAttribute('aria-pressed','false');sourceToggle.innerHTML='Snap off';};listeners.click({target:copies[2]});assert.equal(copies[2].getAttribute('aria-pressed'),'false');assert.equal(copies[2].innerHTML,'Snap off');syncControlCopies(el);assert.equal(copies[1].disabled,false);await Promise.resolve();
 }finally{globalThis.document=previous;}});
